import type { StringEntry } from '@/lib/i18n'

/** UI strings for this area — every entry needs both \r\ and \en\. */
export const catalogStrings: Record<string, StringEntry> = {
  'cat.breadcrumbHome': { ar: 'الرئيسية', en: 'Home' },
  'cat.breadcrumbFabrics': { ar: 'الأقمشة', en: 'Fabrics' },
  'cat.eyebrow': { ar: 'معرض الخامات', en: 'Fabric gallery' },
  'cat.allFabricsTitle': { ar: 'كل الأقمشة', en: 'All fabrics' },
  'cat.countFabrics': { ar: '{n} خامة في المعرض', en: '{n} fabrics on display' },
  'cat.statusLoading': { ar: 'جارٍ الاتصال بالخادم', en: 'Connecting to the server' },
  'cat.statusFallback': { ar: 'تعذّر الاتصال — المحتوى المحفوظ يعمل', en: 'Connection failed — showing saved content' },
  'cat.statusLive': { ar: 'متصل بالخادم — تحديث مباشر', en: 'Connected — live updates' },
  'cat.sortBy': { ar: 'ترتيب حسب', en: 'Sort by' },
  'cat.sortFeatured': { ar: 'الترتيب الافتراضي', en: 'Default order' },
  'cat.sortPriceAsc': { ar: 'السعر: الأقل أولاً', en: 'Price: low to high' },
  'cat.sortPriceDesc': { ar: 'السعر: الأعلى أولاً', en: 'Price: high to low' },
  'cat.chipsAria': { ar: 'تصفحي الأقمشة حسب القسم', en: 'Browse fabrics by category' },
  'cat.chipAria': { ar: '{label}، {n} خامة', en: '{label}, {n} fabrics' },
  'cat.chipAll': { ar: 'كل الخامات', en: 'All fabrics' },
  'cat.filterOpen': { ar: 'فتح التصفية', en: 'Open filters' },
  'cat.filterOpenActive': { ar: 'فتح التصفية، {n} فلتر مفعّل', en: 'Open filters, {n} active' },
  'cat.filterBtn': { ar: 'تصفية', en: 'Filter' },
  'cat.filterFabrics': { ar: 'تصفية الأقمشة', en: 'Filter fabrics' },
  'cat.resultsAria': { ar: 'نتائج الأقمشة', en: 'Fabric results' },
  'cat.searchLabel': { ar: 'ابحثي في النتائج', en: 'Search within results' },
  'cat.searchPlaceholder': { ar: 'ابحثي باسم القماش أو اللون أو الاستخدام', en: 'Search by fabric name, color, or use' },
  'cat.clearSearch': { ar: 'مسح البحث', en: 'Clear search' },
  'cat.searchBtn': { ar: 'بحث', en: 'Search' },
  'cat.activeFilters': { ar: 'مرشحات:', en: 'Filters:' },
  'cat.filterSearch': { ar: 'بحث: {q}', en: 'Search: {q}' },
  'cat.filterCategory': { ar: 'قسم: {name}', en: 'Category: {name}' },
  'cat.inStockOnly': { ar: 'متوفر فقط', en: 'In stock only' },
  'cat.clearAll': { ar: 'مسح الكل', en: 'Clear all' },
  'cat.statShow': { ar: 'عرض', en: 'Showing' },
  'cat.statOfTotal': { ar: 'من {total} خامة', en: 'of {total} fabrics' },
  'cat.statAvgPrice': { ar: 'متوسط السعر', en: 'Average price' },
  'cat.statAvailable': { ar: 'متوفر الآن', en: 'Available now' },
  'cat.filterResultsTitle': { ar: 'تصفية النتائج', en: 'Filter results' },
  'cat.closeFilter': { ar: 'إغلاق التصفية', en: 'Close filters' },
  'cat.showResults': { ar: 'عرض النتائج ({n})', en: 'Show results ({n})' },
  'cat.filterPanelTitle': { ar: 'التصفية', en: 'Filters' },
  'cat.fabricType': { ar: 'نوع القماش', en: 'Fabric type' },
  'cat.allCategories': { ar: 'كل الأقسام', en: 'All categories' },
  'cat.stretchLegend': { ar: 'المرونة', en: 'Stretch' },
  'cat.stretchAll': { ar: 'الكل', en: 'All' },
  'cat.stretchYes': { ar: 'مطاطي', en: 'Stretchy' },
  'cat.stretchNon': { ar: 'غير مطاطي', en: 'Non-stretch' },
  'cat.priceRange': { ar: 'نطاق السعر', en: 'Price range' },
  'cat.priceFrom': { ar: 'من', en: 'From' },
  'cat.priceTo': { ar: 'إلى', en: 'To' },
  'cat.minPricePlaceholder': { ar: 'السعر الأدنى', en: 'Min price' },
  'cat.minPriceAria': { ar: 'السعر الأدنى بالدينار العراقي', en: 'Minimum price in Iraqi dinar' },
  'cat.maxPricePlaceholder': { ar: 'السعر الأعلى', en: 'Max price' },
  'cat.maxPriceAria': { ar: 'السعر الأعلى بالدينار العراقي', en: 'Maximum price in Iraqi dinar' },
  'cat.stockOnly': { ar: 'المتوفر فقط', en: 'Available only' },
  'cat.showAllFabrics': { ar: 'عرض كل الخامات', en: 'Show all fabrics' },
  'cat.removeFilter': { ar: 'إزالة {label}', en: 'Remove {label}' },
  'cat.emptyTitle': { ar: 'لم نجد خامة بهذه المواصفات', en: 'No fabric matches these criteria' },
  'cat.emptyHint': { ar: 'جرّبي كلمة بحث مختلفة أو أزيلي بعض الفلاتر لتظهر لك كل الخامات المتاحة في المعرض.', en: 'Try a different search or clear some filters to see every fabric on display.' },
  'cat.emptyAction': { ar: 'عرض كل الأقمشة', en: 'Show all fabrics' },
  'cat.priceFromLabel': { ar: 'من {price}', en: 'From {price}' },
  'cat.priceUntilLabel': { ar: 'حتى {price}', en: 'Up to {price}' },

  'card.wishRemove': { ar: 'إزالة {name} من المفضلة', en: 'Remove {name} from favorites' },
  'card.wishAdd': { ar: 'إضافة {name} إلى المفضلة', en: 'Add {name} to favorites' },
  'card.addHalfAria': { ar: 'أضيفي نصف متر من {name} إلى السلة', en: 'Add half a meter of {name} to the cart' },
  'card.detailsAria': { ar: 'عرض تفاصيل {name}', en: 'View details for {name}' },
  'card.badgeStyle': { ar: 'ستايل', en: 'Style' },
  'card.badgeNew': { ar: 'جديد', en: 'New' },
  'card.badgeLow': { ar: 'كمية محدودة', en: 'Low stock' },
  'card.badgeSold': { ar: 'غير متوفر', en: 'Out of stock' },
  'card.perMeter': { ar: '/م', en: '/m' },
  'card.soldOut': { ar: 'نفد المخزون', en: 'Sold out' },
  'card.addHalf': { ar: 'أضيفي نصف متر', en: 'Add half meter' },
  'card.loadingAria': { ar: 'جارٍ تحميل الأقمشة', en: 'Loading fabrics' },
  'card.addToCartAria': { ar: 'إضافة {name} إلى السلة', en: 'Add {name} to the cart' },

  'fav.breadcrumbHome': { ar: 'الرئيسية', en: 'Home' },
  'fav.title': { ar: 'المفضلة', en: 'Favorites' },
  'fav.countOne': { ar: 'خامة واحدة بانتظارك', en: '1 fabric waiting for you' },
  'fav.countTwo': { ar: 'خامتان بانتظارك', en: '2 fabrics waiting for you' },
  'fav.countFew': { ar: '{n} خامات بانتظارك', en: '{n} fabrics waiting for you' },
  'fav.countMany': { ar: '{n} خامة بانتظارك', en: '{n} fabrics waiting for you' },
  'fav.emptyTitle': { ar: 'لم تحفظي أقمشة بعد', en: 'You haven’t saved any fabrics yet' },
  'fav.emptyHint': { ar: 'اضغطي على القلب في أي خامة لتظهر هنا، ثم انقليها إلى السلة بنصف متر أو أكثر بضغطة واحدة.', en: 'Tap the heart on any fabric to keep it here, then move it to your cart with half a meter or more in one tap.' },
  'fav.browse': { ar: 'اكتشفي الأقمشة', en: 'Browse fabrics' },
  'fav.guide': { ar: 'دليل اختيار القماش', en: 'Fabric selection guide' },
  'fav.suggested': { ar: 'أقسام مقترحة:', en: 'Suggested categories:' },
  'fav.eyebrow': { ar: 'اختياراتك المحفوظة', en: 'Your saved picks' },
  'fav.continue': { ar: 'متابعة التسوق', en: 'Continue shopping' },
  'fav.removeAria': { ar: 'إزالة {name} من المفضلة', en: 'Remove {name} from favorites' },
  'fav.removeBtn': { ar: 'إزالة', en: 'Remove' },
  'fav.details': { ar: 'تفاصيل الخامة', en: 'Fabric details' },
  'fav.note': { ar: 'اضغطي «أضيفي ٠٫٥ م» على أي بطاقة لنقلها إلى السلة مباشرة، أو القلب لإزالتها من هنا.', en: 'Tap “Add 0.5 m” on any card to send it straight to your cart, or the heart to remove it from here.' },

  'search.title': { ar: 'البحث في الأقمشة', en: 'Search fabrics' },
  'search.close': { ar: 'إغلاق البحث', en: 'Close search' },
  'search.label': { ar: 'ابحثي عن قماش أو لون أو استخدام', en: 'Search for a fabric, color, or use' },
  'search.placeholder': { ar: 'ابحثي عن قماش، لون أو استخدام', en: 'Search fabric, color, or use' },
  'search.clear': { ar: 'مسح البحث', en: 'Clear search' },
  'search.submit': { ar: 'بحث', en: 'Search' },
  'search.popular': { ar: 'بحث شائع', en: 'Popular searches' },
  'search.resultsCount': { ar: '{n} نتائج مناسبة', en: '{n} matching results' },
  'search.noResults': { ar: 'لا توجد نتائج مطابقة', en: 'No matching results' },
  'search.sugStretch': { ar: 'قماش مطاطي', en: 'Stretchy fabric' },
  'search.sugBlack': { ar: 'قماش أسود', en: 'Black fabric' },
  'search.sugEmbroidered': { ar: 'مطرز', en: 'Embroidered' },
  'search.sugSequined': { ar: 'ترتر', en: 'Sequined' },
  'search.sugEvening': { ar: 'فساتين سهرة', en: 'Evening dresses' },
  'search.sugNonStretch': { ar: 'غير مطاطي', en: 'Non-stretch' },
}

export const typeLabelsEn: Record<string, string> = { plain: 'Plain', patterned: 'Printed', stretch: 'Stretchy', embroidered: 'Embroidered', sequined: 'Sequined', style: 'Style', harvard: 'Harvard' }

const typeKeyByAr: Record<string, string> = {
  'سادة': 'plain',
  'مزخرف': 'patterned',
  'مطاطي': 'stretch',
  'مطرز': 'embroidered',
  'ترتر': 'sequined',
  'ستايل': 'style',
  'هارفرد': 'harvard',
}

export const typeLabelEn = (type: string): string => typeLabelsEn[typeKeyByAr[type] ?? type] ?? type
