import type { StringEntry } from '@/lib/i18n'

/** Core UI strings owned by the i18n foundation (App shell, helpers, discovery). */
export const coreStrings: Record<string, StringEntry> = {
  'core.skipLink': { ar: 'تخطي إلى المحتوى', en: 'Skip to content' },
  'core.noticeUnavailable': { ar: 'هذه الخامة غير متوفرة حالياً', en: 'This fabric is currently unavailable' },
  'core.noticeCapped': { ar: 'أضيفت الكمية المتاحة فقط من «{name}»', en: 'Only the available quantity of “{name}” was added' },
  'core.noticeAdded': { ar: 'أضيف «{name}» إلى السلة', en: 'Added “{name}” to the cart' },
  'core.noticeWishRemoved': { ar: 'أزيل القماش من المفضلة', en: 'Fabric removed from favorites' },
  'core.noticeWishAdded': { ar: 'حُفظ القماش في المفضلة', en: 'Fabric saved to favorites' },
  'core.noticeOrderSaved': { ar: 'تم تسجيل طلبك بنجاح', en: 'Your order was recorded successfully' },
  'core.toastCart': { ar: 'السلة', en: 'Cart' },
  'core.toastWishlist': { ar: 'المفضلة', en: 'Favorites' },
  'core.toastClose': { ar: 'إغلاق التنبيه', en: 'Close notification' },
  'core.langSwitchAria': { ar: 'Switch to English', en: 'التبديل إلى العربية' },
  'core.modalClose': { ar: 'إغلاق {title}', en: 'Close {title}' },
  'core.logoHome': { ar: 'إيفا ستور، الصفحة الرئيسية', en: 'Eva Store — home page' },
  'core.logoName': { ar: 'إيفا ستور', en: 'Eva Store' },
  'core.logoTag': { ar: 'للأقمشة', en: 'fabrics' },
  'core.errorEyebrow': { ar: 'حدث خطأ غير متوقع', en: 'An unexpected error occurred' },
  'core.errorTitle': { ar: 'تعذر عرض هذه الصفحة', en: 'Could not display this page' },
  'core.errorHint': { ar: 'حاولي تحديث الصفحة أو العودة لاحقاً.', en: 'Try refreshing the page or coming back later.' },
  'core.errorRetry': { ar: 'إعادة المحاولة', en: 'Try again' },
  'core.priceOnConfirm': { ar: 'السعر عند التأكيد', en: 'Price on confirmation' },
  'core.priceThousand': { ar: '{n} الف دينار عراقي', en: '{n},000 IQD' },
  'core.priceFull': { ar: '{n} دينار عراقي', en: '{n} IQD' },
  'core.dinarShortThousand': { ar: '{n} الف دينار', en: '{n}K IQD' },
  'core.dinarShort': { ar: '{n} دينار', en: '{n} IQD' },
  'core.metersHalf': { ar: 'نصف متر', en: 'half a meter' },
  'core.metersWord': { ar: 'متر', en: 'meter' },
  'core.metersShortHalf': { ar: 'نصف متر', en: 'half m' },
  'core.metersShortUnit': { ar: 'م', en: 'm' },
  'disc.suitableDailyDresses': { ar: 'مناسب للفساتين اليومية', en: 'Suitable for everyday dresses' },
  'disc.lightComfortable': { ar: 'خامة خفيفة ومريحة', en: 'Light and comfortable fabric' },
  'disc.notSheer': { ar: 'غير شفافة', en: 'Not sheer' },
  'disc.stretchyEasySew': { ar: 'مرنة وسهلة التفصيل', en: 'Stretchy and easy to sew' },
  'disc.heavyForDaily': { ar: 'ثقيلة قليلاً للاستخدام اليومي', en: 'A bit heavy for daily wear' },
  'disc.eveningShine': { ar: 'لمعة مناسبة للسهرة', en: 'Evening-appropriate shine' },
  'disc.elegantDrape': { ar: 'انسيابية أنيقة', en: 'Elegant drape' },
  'disc.mentionedDresses': { ar: 'مذكور للفساتين', en: 'Mentioned for dresses' },
  'disc.comfortableCoverage': { ar: 'تغطية مريحة', en: 'Comfortable coverage' },
  'disc.matteNoShine': { ar: 'مطفي بدون لمعة', en: 'Matte with no shine' },
  'disc.mentionedAbayas': { ar: 'مذكور للعباءات', en: 'Mentioned for abayas' },
  'disc.fullCoverage': { ar: 'تغطية كاملة', en: 'Full coverage' },
  'disc.outerwearWeight': { ar: 'سماكة مناسبة للطبقة الخارجية', en: 'Weight suited for outerwear' },
  'disc.sheerNotForAbaya': { ar: 'شفافة ولا تناسب العباءة', en: 'Sheer — not suited for abayas' },
  'disc.stretchComfort': { ar: 'مرونة في الارتداء', en: 'Stretch for wearing comfort' },
  'disc.mentionedPractical': { ar: 'مذكور لقطع عملية', en: 'Mentioned for practical pieces' },
  'disc.stretchyMovesEasy': { ar: 'مطاطية تسهل الحركة', en: 'Stretchy for easy movement' },
  'disc.practicalCoverage': { ar: 'تغطية عملية', en: 'Practical coverage' },
  'disc.lightOnBody': { ar: 'خفيفة على الجسم', en: 'Light on the body' },
  'disc.lessSuitablePractical': { ar: 'لمعة أقل ملاءمة للاستخدام العملي', en: 'Shine is less suited for practical wear' },
  'disc.darkShades': { ar: 'درجات داكنة', en: 'Dark shades' },
  'disc.paleColor': { ar: 'فاتح اللون', en: 'Pale color' },
  'disc.paleShades': { ar: 'درجات فاتحة', en: 'Pale shades' },
  'disc.darkColor': { ar: 'داكن اللون', en: 'Dark color' },
  'disc.shinySurface': { ar: 'سطح لامع', en: 'Shiny surface' },
  'disc.matteSurface': { ar: 'سطح مطفي', en: 'Matte surface' },
  'disc.quietColor': { ar: 'لون هادئ غير لامع', en: 'Quiet non-shiny color' },
  'disc.easyToMatch': { ar: 'سهل التنسيق', en: 'Easy to match' },
  'disc.isStretchy': { ar: 'مطاطية', en: 'Stretchy' },
  'disc.notStretchy': { ar: 'غير مطاطية', en: 'Not stretchy' },
}
