import type { StringEntry } from '@/lib/i18n'

/** UI strings for this area — every entry needs both \r\ and \en\. */
export const headerStrings: Record<string, StringEntry> = {
  'header.nav.home': { ar: 'الرئيسية', en: 'Home' },
  'header.nav.catalog': { ar: 'الأقمشة', en: 'Fabrics' },
  'header.nav.favorites': { ar: 'المفضلة', en: 'Favorites' },
  'header.nav.guide': { ar: 'دليل الأقمشة', en: 'Fabric guide' },
  'header.nav.about': { ar: 'من نحن', en: 'About us' },
  'header.nav.contact': { ar: 'تواصلي', en: 'Contact us' },
  'header.nav.tracking': { ar: 'تتبع الطلب', en: 'Order tracking' },
  'header.nav.policies': { ar: 'السياسات', en: 'Policies' },
  'header.nav.allFabrics': { ar: 'كل الأقمشة', en: 'All fabrics' },
  'header.nav.cart': { ar: 'سلة المشتريات', en: 'Shopping cart' },
  'header.nav.contactUs': { ar: 'تواصلي معنا', en: 'Contact us' },
  'header.nav.policiesShipping': { ar: 'السياسات والشحن', en: 'Policies and shipping' },
  'header.group.shopping': { ar: 'التسوق', en: 'Shopping' },
  'header.group.service': { ar: 'خدمة العملاء', en: 'Customer service' },
  'header.announcementBar': { ar: 'إعلان المتجر', en: 'Store announcement' },
  'header.announceContact': { ar: 'تواصلي معنا عبر الموقع', en: 'Contact us on the site' },
  'header.mainNav': { ar: 'التنقل الرئيسي', en: 'Main navigation' },
  'header.openSearch': { ar: 'فتح البحث في الأقمشة', en: 'Open fabric search' },
  'header.favoritesAria': { ar: 'المفضلة، {count} عناصر', en: 'Favorites, {count} items' },
  'header.cartAria': { ar: 'السلة، {meters}', en: 'Cart, {meters}' },
  'header.openMenu': { ar: 'فتح قائمة التنقل', en: 'Open navigation menu' },
  'header.quickNav': { ar: 'تنقل سريع', en: 'Quick navigation' },
  'header.menuTitle': { ar: 'قائمة التنقل', en: 'Navigation menu' },
  'header.closeMenu': { ar: 'إغلاق القائمة', en: 'Close menu' },
  'header.chip.trackOrder': { ar: 'تتبّع الطلب', en: 'Track order' },

  'foot.nav.about': { ar: 'من نحن', en: 'About us' },
  'foot.nav.guide': { ar: 'دليل الأقمشة', en: 'Fabric guide' },
  'foot.nav.tracking': { ar: 'تتبّع الطلب', en: 'Track order' },
  'foot.nav.contact': { ar: 'تواصلي معنا', en: 'Contact us' },
  'foot.nav.policies': { ar: 'السياسات', en: 'Policies' },
  'foot.tagline': { ar: 'معرض أقمشة عربي يساعدك على معرفة الخامة والمرونة واللون قبل اختيار القطعة.', en: 'An Arabic fabric showroom that helps you understand the material, stretch and colour before you pick your piece.' },
  'foot.contactViaSite': { ar: 'تواصلي معنا عبر الموقع', en: 'Contact us on the site' },
  'foot.colFabrics': { ar: 'الأقمشة', en: 'Fabrics' },
  'foot.allFabrics': { ar: 'كل الأقمشة', en: 'All fabrics' },
  'foot.colInfo': { ar: 'معلومات', en: 'Information' },
  'foot.privacy': { ar: 'الخصوصية', en: 'Privacy' },
  'foot.returns': { ar: 'الإرجاع والتبديل', en: 'Returns and exchanges' },
  'foot.adminLogin': { ar: 'تسجيل الدخول كمدير', en: 'Admin login' },
  'foot.colContact': { ar: 'تواصلي معنا', en: 'Contact us' },
  'foot.contactForm': { ar: 'نموذج التواصل في الموقع', en: 'Contact form on the site' },
  'foot.trackStatus': { ar: 'تتبّع حالة الطلب', en: 'Track your order status' },
  'foot.colServiceArea': { ar: 'نطاق الخدمة', en: 'Service area' },
  'foot.deliveryRange': { ar: 'نوصل إلى {list} وجميع محافظات العراق.', en: 'We deliver to {list} and every governorate in Iraq.' },
  'foot.listSeparator': { ar: '،', en: ',' },
  'foot.deliveryFee': { ar: 'توصيل ٥ آلاف دينار', en: 'Delivery 5,000 dinars' },
  'foot.pricesNote': { ar: 'الأسعار والمواصفات تُراجع قبل تأكيد الطلب', en: 'Prices and specifications are reviewed before your order is confirmed' },

  'home.categoriesAria': { ar: 'أقسام المعرض', en: 'Showroom categories' },
  'home.showAllFabrics': { ar: 'عرض كل الأقمشة', en: 'Show all fabrics' },
  'home.discover': { ar: 'اكتشفي', en: 'Discover' },
  'home.newAria': { ar: 'وصل حديثاً', en: 'New arrivals' },
  'home.seeNew': { ar: 'شاهدي الجديد', en: 'See what is new' },
  'home.storyEyebrow': { ar: 'قصة العلامة', en: 'Our story' },
  'home.storyImageAlt': { ar: 'صوف ميتالك', en: 'Metallic wool' },
  'home.storyText2': { ar: 'نصمم تجربتنا لتكون قريبة منك: صور واضحة، مواصفات مفهومة، وخدمة تساعدك قبل الطلب وبعده.', en: 'We design our experience to stay close to you: clear photos, understandable specs, and support before and after you order.' },
  'home.storyCta': { ar: 'اعرفي أكثر عن إيفا', en: 'Learn more about Eva' },
  'home.trustAria': { ar: 'ضمانات المتجر', en: 'Store guarantees' },
  'home.faq.questionNumber': { ar: 'سؤال {n}', en: 'Question {n}' },

  'home.discovery.eyebrow': { ar: 'اكتشاف موجّه', en: 'Guided discovery' },
  'home.discovery.title1': { ar: 'دعي القماش المناسب', en: 'Let the perfect fabric' },
  'home.discovery.title2': { ar: 'يقترب منك.', en: 'come your way.' },
  'home.discovery.intro': { ar: 'ثلاث خطوات صغيرة تساعدك على تضييق الخيارات قبل التصفح.', en: 'Three small steps to narrow down your options before you browse.' },
  'home.discovery.progress': { ar: 'الخطوة {step} من ٣', en: 'Step {step} of 3' },
  'home.discovery.restart': { ar: 'ابدئي من جديد', en: 'Start over' },
  'home.discovery.resultsTitle': { ar: 'اقتراحاتنا لك', en: 'Our suggestions for you' },
  'home.discovery.matchFallback': { ar: 'خامة مطابقة لاختياراتك', en: 'A fabric that matches your choices' },
  'home.discovery.viewProduct': { ar: 'عرض {name}', en: 'View {name}' },
  'home.discovery.view': { ar: 'شاهدي', en: 'View' },
  'home.discovery.showAllMatches': { ar: 'عرض كل الأقمشة المطابقة', en: 'Show all matching fabrics' },
  'home.discovery.viewSuggestions': { ar: 'شاهدي اقتراحاتي', en: 'View my suggestions' },
  'home.discovery.q1': { ar: 'ماذا ستصنعين؟', en: 'What will you make?' },
  'home.discovery.q1.dress': { ar: 'فستان يومي', en: 'Everyday dress' },
  'home.discovery.q1.evening': { ar: 'فستان سهرة', en: 'Evening dress' },
  'home.discovery.q1.abaya': { ar: 'عباءة أو برنوش', en: 'Abaya or burnous' },
  'home.discovery.q1.practical': { ar: 'قطعة عملية', en: 'A practical piece' },
  'home.discovery.q2': { ar: 'هل تحتاجين مرونة؟', en: 'Do you need stretch?' },
  'home.discovery.q2.yes': { ar: 'نعم، مطاطي', en: 'Yes, stretchy' },
  'home.discovery.q2.no': { ar: 'لا، غير مطاطي', en: 'No, not stretchy' },
  'home.discovery.q2.either': { ar: 'لا يهمني', en: 'It does not matter' },
  'home.discovery.q3': { ar: 'ما اللون الأقرب لك؟', en: 'Which colour feels closest to you?' },
  'home.discovery.q3.dark': { ar: 'داكن', en: 'Dark' },
  'home.discovery.q3.light': { ar: 'فاتح', en: 'Light' },
  'home.discovery.q3.shiny': { ar: 'لامع', en: 'Shiny' },
  'home.discovery.q3.neutral': { ar: 'محايد', en: 'Neutral' },

  'home.steps.eyebrow': { ar: 'ثلاث خطوات فقط', en: 'Just three steps' },
  'home.steps.title': { ar: 'كيف تطلب؟', en: 'How to order' },
  'home.steps.description': { ar: 'من اختيار القماش إلى باب المنزل', en: 'From picking your fabric to your front door' },
  'home.steps.cta': { ar: 'ابدئي التسوق', en: 'Start shopping' },
  'home.steps.browseAll': { ar: 'تصفحي كل الأقمشة', en: 'Browse all fabrics' },
  'home.steps.s1.index': { ar: '٠١', en: '01' },
  'home.steps.s1.title': { ar: 'اختاري القماش', en: 'Pick your fabric' },
  'home.steps.s1.text': { ar: 'تصفحي الأقسام وقارني الصور والمواصفات: السماكة والمرونة والشفافية قبل أن تقرري.', en: 'Browse the sections and compare photos and specs: weight, stretch and opacity before you decide.' },
  'home.steps.s1.hint': { ar: 'بدون تسجيل', en: 'No sign-up needed' },
  'home.steps.s2.index': { ar: '٠٢', en: '02' },
  'home.steps.s2.title': { ar: 'حددي الكمية', en: 'Choose your quantity' },
  'home.steps.s2.text': { ar: 'أضيفي نصف متر فأكثر إلى السلة، واختاري اللون المناسب، ونؤكد التوافر معك عبر الهاتف عند تأكيد الطلب.', en: 'Add half a meter or more to your cart, pick your colour, and we will confirm availability by phone when you place the order.' },
  'home.steps.s2.hint': { ar: 'من نصف متر', en: 'From half a meter' },
  'home.steps.s3.index': { ar: '٠٣', en: '03' },
  'home.steps.s3.title': { ar: 'أرسلي الطلب وادفعي', en: 'Send your order and pay' },
  'home.steps.s3.text': { ar: 'أكملي اسمك ومحافظتك وعنوانك، ثم ادفعي نقداً عند استلام الطلب في باب المنزل.', en: 'Fill in your name, governorate and address, then pay in cash when the order arrives at your door.' },
  'home.steps.s3.hint': { ar: 'دفع عند الاستلام', en: 'Cash on delivery' },

  'home.promo.aria': { ar: 'توصيل مجاني للطلبات فوق {price}', en: 'Free delivery on orders over {price}' },
  'home.promo.cta': { ar: 'اطلبي الآن', en: 'Order now' },

  'home.newsletter.aria': { ar: 'اشتراك بالنشرة', en: 'Newsletter signup' },
  'home.newsletter.emailLabel': { ar: 'البريد الإلكتروني', en: 'Email address' },
  'home.newsletter.emailPlaceholder': { ar: 'بريدك الإلكتروني', en: 'Your email address' },
  'home.newsletter.submit': { ar: 'اشتراك بالبريد', en: 'Subscribe' },
  'home.newsletter.error': { ar: 'يرجى إدخال بريد إلكتروني صحيح.', en: 'Please enter a valid email address.' },
  'home.newsletter.sent': { ar: 'تم تسجيل بريدك في النشرة، ستصلك أحدث القطع والأخبار.', en: 'Your email is on the list — the latest pieces and news will reach your inbox.' },
  'home.newsletter.noteLead': { ar: 'أو اطلبي استشارة في اختيار القماش عبر', en: 'Or ask for help choosing your fabric through' },
  'home.newsletter.noteLink': { ar: 'نموذج التواصل في الموقع', en: 'the contact form on the site' },
  'home.newsletter.subject': { ar: 'اشتراك في نشرة إيفا ستور', en: 'Eva Store newsletter subscription' },
  'home.newsletter.body': { ar: 'طلب اشتراك في النشرة من الموقع\nالبريد: {email}', en: 'Newsletter subscription request from the website\nEmail: {email}' },

  'home.hero.browse': { ar: 'تصفحي الأقمشة', en: 'Browse fabrics' },
  'home.hero.discoverNew': { ar: 'اكتشفي الجديد', en: 'Discover the latest' },
  'home.hero.next': { ar: 'الصورة التالية', en: 'Next image' },
  'home.hero.prev': { ar: 'الصورة السابقة', en: 'Previous image' },
  'home.hero.dots': { ar: 'صور الغلاف', en: 'Cover images' },
  'home.stats.fabricsLabel': { ar: 'خامة متاحة', en: 'Available fabrics' },
  'home.stats.fabricsTrend': { ar: 'تشكيلة تتجدد', en: 'A range that keeps growing' },
  'home.stats.categoriesLabel': { ar: 'أقسام مختارة', en: 'Curated categories' },
  'home.stats.categoriesTrend': { ar: 'لكل مشروع', en: 'For every project' },
  'home.stats.deliveryLabel': { ar: 'محافظة للتوصيل', en: 'Governorates we deliver to' },
  'home.stats.deliveryTrend': { ar: 'توصيل ٥ آلاف دينار', en: 'Delivery 5,000 dinars' },
  'home.stats.cashLabel': { ar: 'دفع عند الاستلام', en: 'Cash on delivery' },
  'home.stats.cashTrend': { ar: 'مريح وآمن', en: 'Easy and secure' },
  'home.stats.percent': { ar: '٪', en: '%' },
  'home.slide.colorful': { ar: 'ألوان كريب متنوعة', en: 'Vibrant crepe colors' },
  'home.slide.sequin': { ar: 'تطريز فضي بلمعة اللؤلؤ', en: 'Silver sequin embroidery' },
  'home.slide.pearl': { ar: 'قماش وردي وبني مع لمسة اللؤلؤ', en: 'Pink & brown with pearl beading' },
  'home.slide.stripe': { ar: 'مخطط كحلي وعنابي', en: 'Navy & burgundy stripes' },
}

export const routeLabelsEn: Record<string, string> = {
  home: 'Home',
  catalog: 'Fabrics',
  new: 'New arrivals',
  favorites: 'Favorites',
  about: 'About us',
  guide: 'Fabric guide',
  contact: 'Contact us',
  tracking: 'Order tracking',
  policies: 'Policies',
  cart: 'Cart',
}

export const discoveryEngineValues: Record<string, string> = {
  'home.discovery.q1.dress': 'فستان يومي',
  'home.discovery.q1.evening': 'فستان سهرة',
  'home.discovery.q1.abaya': 'عباءة أو برنوش',
  'home.discovery.q1.practical': 'قطعة عملية',
  'home.discovery.q2.yes': 'نعم، مطاطي',
  'home.discovery.q2.no': 'لا، غير مطاطي',
  'home.discovery.q3.dark': 'داكن',
  'home.discovery.q3.light': 'فاتح',
  'home.discovery.q3.shiny': 'لامع',
  'home.discovery.q3.neutral': 'محايد',
}

export const trustItemsEn: { title: string; description: string; icon: string }[] = [
  { title: 'Delivery across Iraq', description: 'All governorates', icon: 'truck' },
  { title: 'Delivery 5,000 dinars', description: 'Fixed fee', icon: 'wallet' },
  { title: 'Support on the site', description: 'Before and after you order', icon: 'message' },
  { title: 'A confident choice', description: 'Clear specifications', icon: 'check' },
]

export const homeStoryEn = {
  title: 'Fabrics worth choosing with confidence',
  text: 'Eva Store is an Iraqi space that brings together a varied range with a clear explanation of feel, stretch and colour, so your decision is easier before you order by the meter.',
}

export const guideQuestionsEn: { question: string; answer: string }[] = [
  { question: 'How do I pick the right fabric?', answer: 'Start with the occasion: everyday fabric should be light and comfortable, while special events may call for weight, structure and shine. Check the stretch, opacity and width before you buy.' },
  { question: 'What is the difference between stretchy and non-stretchy?', answer: 'Stretchy fabric contains elastane or spandex, so it stretches and returns to shape. Non-stretchy fabric holds its structure better and suits clearly tailored pieces. Labels in the store follow the actual stretch of the design.' },
  { question: 'How do I know the right width?', answer: 'Width is the measurement from edge to edge, and it is listed in every product spec. The wider the fabric, the less you need for a single piece.' },
  { question: 'How much fabric do I need?', answer: 'A simple piece usually needs between 2 and 2.5 meters, and an abaya between 3 and 4 meters. Add a small margin for cutting and sewing, and half-meter orders are welcome.' },
  { question: 'How do I read the colour description?', answer: 'The photos are a visual sample of the material. Compare the colour with the lighting around you and with similar pieces, and contact us if the shade is critical to your project.' },
]

export const governoratesEn: string[] = [
  'Baghdad', 'Basra', 'Nineveh', 'Erbil', 'Najaf', 'Karbala', 'Al Anbar', 'Diyala',
  'Kirkuk', 'Salah ad Din', 'Wasit', 'Babylon', 'Dhi Qar', 'Maysan', 'Muthanna', 'Al Qadisiyah', 'Duhok', 'Sulaymaniyah',
]
