import type { StringEntry } from '@/lib/i18n'
import type { ProductFaq } from '@/types'

/** UI strings for this area — every entry needs both \r\ and \en\. */
export const infoStrings: Record<string, StringEntry> = {
  // ── About ────────────────────────────────────────────────────────────────
  'about.crumbHome': { ar: 'الرئيسية', en: 'Home' },
  'about.crumbCurrent': { ar: 'من نحن', en: 'About us' },
  'about.eyebrow': { ar: 'من إيفا إلى يدك', en: 'From Eva to your hands' },
  'about.chipOrder': { ar: 'طلب من نصف متر', en: 'Orders from half a meter' },
  'about.chipSpecs': { ar: 'مواصفات مكتوبة', en: 'Written specs' },
  'about.chipDelivery': { ar: 'توصيل لكل العراق', en: 'Delivery across Iraq' },
  'about.point1Num': { ar: '٠١', en: '01' },
  'about.point1Title': { ar: 'وضوح قبل الطلب', en: 'Clarity before ordering' },
  'about.point1Text': { ar: 'مواصفات وخطوات طلب بنصف متر.', en: 'Specs and an ordering path from half a meter.' },
  'about.point2Num': { ar: '٠٢', en: '02' },
  'about.point2Title': { ar: 'اختيار أهدأ', en: 'A calmer choice' },
  'about.point2Text': { ar: 'صور وتفاصيل تساعدك على المقارنة.', en: 'Photos and details that help you compare.' },
  'about.point3Num': { ar: '٠٣', en: '03' },
  'about.point3Title': { ar: 'دعم قريب', en: 'Support close by' },
  'about.point3Text': { ar: 'تواصلي معنا قبل وبعد الطلب.', en: 'Reach out before and after ordering.' },
  'about.imgAlt1': { ar: 'دانتيل فرنسي أمبرودري', en: 'French embroidered lace' },
  'about.imgAlt2': { ar: 'لمسة البوكلي ونسيج الأنكورا', en: 'Bouclé touch and Ankora weave' },
  'about.storyEyebrow': { ar: 'قصة البراند', en: 'The brand story' },
  'about.storyTitle': { ar: 'من فيديو قصير إلى معرض كامل.', en: 'From a short video to a full showroom.' },
  'about.storyLink': { ar: 'اقرئي دليل الأقمشة', en: 'Read the fabric guide' },
  'about.storyP1': {
    ar: 'من حسابنا على إنستغرام بدأنا نعرض الأقمشة بالصور والفيديو: نُظهر اللون في الضوء الطبيعي، ونشرح الوزن والمرونة والشفافية في تسجيل صوتي قصير قبل أن يصلك القماش.',
    en: 'We started on Instagram, showing fabrics in photos and video: the color in natural light, and the weight, stretch and opacity explained in a short voice note before the fabric reaches you.',
  },
  'about.storyP2': {
    ar: 'اليوم تجد كل ذلك في مكان واحد: معرض يضم {count} خامة بمواصفات مكتوبة، وطلب يبدأ من نصف متر، وتوصيل إلى جميع المحافظات العراقية مع تأكيد يدوي لكل طلب.',
    en: 'Today you find it all in one place: a showroom of {count} fabrics with written specs, orders from half a meter, delivery to every Iraqi governorate and a manual confirmation for each order.',
  },
  'about.statsEyebrow': { ar: 'أرقام تختصر الرحلة', en: 'Numbers that sum up the journey' },
  'about.statsTitle': { ar: 'إيفا في أربعة أرقام', en: 'Eva in four numbers' },
  'about.statsText': { ar: 'أرقام فعلية من المعرض ومن مكتبة المنشورات على إنستغرام.', en: 'Real numbers from the showroom and our Instagram post library.' },
  'about.stat1Label': { ar: 'خامة في المعرض', en: 'Fabrics in the showroom' },
  'about.stat1Note': { ar: 'كلها بصورة ومواصفات مكتوبة', en: 'All with photos and written specs' },
  'about.stat2Label': { ar: 'أقسام للتصنيف', en: 'Categories to filter by' },
  'about.stat2Note': { ar: 'ستايلات، مطرز، سادة، مطاطي، ترتر، مزخرف، هارفرد', en: 'Styles, embroidered, plain, stretch, tulle, patterned, Harvard' },
  'about.stat3Label': { ar: 'محافظة نغطيها', en: 'Governorates we cover' },
  'about.stat3Note': { ar: 'توصيل إلى كل العراق', en: 'Delivery across all of Iraq' },
  'about.stat4Label': { ar: 'منشور على إنستغرام', en: 'Posts on Instagram' },
  'about.stat4Note': { ar: 'من حسابنا @x__illc', en: 'From our account @x__illc' },
  'about.valuesEyebrow': { ar: 'ما نؤمن به', en: 'What we believe in' },
  'about.valuesTitle': { ar: 'أربع قيم تحكم كل قرار', en: 'Four values behind every decision' },
  'about.valuesText': { ar: 'من اختيار الخامة إلى طريقة الرد على رسالتك.', en: 'From picking the fabric to how we reply to your message.' },
  'about.value1Title': { ar: 'وضوح قبل الشراء', en: 'Clarity before you buy' },
  'about.value1Text': { ar: 'نكتب الشفافية والمرونة والوزن كما هي، بلا مبالغة ولا وعود مبهمة.', en: 'We list opacity, stretch and weight exactly as they are — no hype, no vague promises.' },
  'about.value2Title': { ar: 'جودة تُلمَس', en: 'Quality you can feel' },
  'about.value2Text': { ar: 'نراجع النسيج والتشطيب والثبات قبل أن تدخل الخامة إلى المعرض.', en: 'We check the weave, finish and colorfastness before a fabric enters the showroom.' },
  'about.value3Title': { ar: 'قرب من العميل', en: 'Close to the customer' },
  'about.value3Text': { ar: 'نسأل عن قصتك قبل أن نقترح الخامة، ونبقى معك حتى الاستلام.', en: 'We ask about your project before suggesting a fabric, and stay with you until delivery.' },
  'about.value4Title': { ar: 'ابدئي من نصف متر', en: 'Start from half a meter' },
  'about.value4Text': { ar: 'لا نفرض كميات كبيرة؛ اطلبي ما تحتاجينه فعلاً وزيدي لاحقاً.', en: 'No big minimums — order what you actually need and add more later.' },
  'about.timelineEyebrow': { ar: 'الخط الزمني', en: 'Timeline' },
  'about.timelineTitle': { ar: 'كيف وصلنا إلى هنا', en: 'How we got here' },
  'about.timelineChip': { ar: 'من إنستغرام إلى متجر', en: 'From Instagram to a store' },
  'about.timeline1Year': { ar: 'البداية', en: 'The start' },
  'about.timeline1Title': { ar: 'من حساب إنستغرام', en: 'An Instagram account' },
  'about.timeline1Text': {
    ar: 'نعرض الأقمشة بالصور والفيديو ونشرح الخامة في تسجيل قصير قبل الطلب — أكثر من ٢٠١ منشوراً حتى الآن.',
    en: 'Fabrics shown in photos and video, with the material explained in a short recording before you order — over 201 posts so far.',
  },
  'about.timeline2Year': { ar: 'التوثيق', en: 'Documentation' },
  'about.timeline2Title': { ar: 'بطاقة لكل قماش', en: 'A card for every fabric' },
  'about.timeline2Text': {
    ar: 'نستخرج من كل منشور وفيديو التركيب والعرض والوزن والمرونة والشفافية، ونضعها أمام الصورة بصيغة مكتوبة.',
    en: 'From every post and video we extract composition, width, weight, stretch and opacity, and put them next to the photo in writing.',
  },
  'about.timeline3Year': { ar: 'الآن', en: 'Now' },
  'about.timeline3Title': { ar: 'متجر أونلاين', en: 'An online store' },
  'about.timeline3Text': {
    ar: '{count} خامة بالمواصفات كاملة، طلب يبدأ من نصف متر، وتوصيل إلى جميع المحافظات العراقية برسوم ثابتة.',
    en: '{count} fabrics with full specs, orders from half a meter, and delivery to every Iraqi governorate at a fixed fee.',
  },
  'about.ctaEyebrow': { ar: 'الخطوة التالية', en: 'Next step' },
  'about.ctaTitle': { ar: 'جاهزة لتختاري خامتك الأولى؟', en: 'Ready to pick your first fabric?' },
  'about.ctaText': {
    ar: 'ابدئي من المعرض لتتصفّحي التفاصيل، أو ارسلي لنا ما تبحثين عنه وسنقترح عليك بديلة مناسبة.',
    en: 'Browse the showroom for the details, or send us what you are looking for and we will suggest a good alternative.',
  },
  'about.ctaBrowse': { ar: 'تصفحي الأقمشة', en: 'Browse fabrics' },
  'about.ctaAsk': { ar: 'اسألينا عبر الموقع', en: 'Ask us on the site' },

  // ── Fabric guide ─────────────────────────────────────────────────────────
  'guide.crumbHome': { ar: 'الرئيسية', en: 'Home' },
  'guide.crumbCurrent': { ar: 'دليل الأقمشة', en: 'Fabric guide' },
  'guide.heroEyebrow': { ar: 'تعلّمي قبل أن تختاري', en: 'Learn before you choose' },
  'guide.heroTitle': { ar: 'دليل الأقمشة الشامل', en: 'The complete fabric guide' },
  'guide.heroText': {
    ar: 'كل خامة لها إيقاعها وطريقة عناية مختلفة. ابدأي من هذه الأسئلة الثلاثة، ثم اقرئي الإجابات السريعة، وأخيراً افتحي صفحة المنتج لتفاصيل الخامة التي تعجبك.',
    en: 'Every fabric has its own drape and care routine. Start with these three questions, then read the quick answers, and finally open the product page for the fabric you like.',
  },
  'guide.quickEyebrow': { ar: 'ابدئي من هنا', en: 'Start here' },
  'guide.quickTitle': { ar: 'إجابات سريعة على أشهر الأسئلة', en: 'Quick answers to the most common questions' },
  'guide.quickText': {
    ar: 'لكل سؤال أكثر من إجابة مختصرة — اضغطي السؤال لتظهر كل الإجابات، أو اقرئي الدليل كاملاً.',
    en: 'Each question has several short answers — tap the question to see them all, or read the full guide.',
  },
  'guide.quickLink': { ar: 'أو اقرئي الدليل الكامل', en: 'Or read the full guide' },
  'guide.stepsAria': { ar: 'ثلاثة أسئلة قبل الشراء', en: 'Three questions before buying' },
  'guide.stepChip1': { ar: 'الخطوة ١', en: 'Step 1' },
  'guide.stepChip2': { ar: 'الخطوة ٢', en: 'Step 2' },
  'guide.stepChip3': { ar: 'الخطوة ٣', en: 'Step 3' },
  'guide.step1Title': { ar: 'حددي الاستخدام', en: 'Define the use' },
  'guide.step1Text': {
    ar: 'فستان يومي، سهرة، عباءة، بناطيل أو قطعة عملية؟ الاستخدام يضيّق الخيارات إلى خامات معدودة.',
    en: 'Everyday dress, evening wear, abaya, trousers or a practical piece? The use narrows it down to a handful of fabrics.',
  },
  'guide.step2Title': { ar: 'قارني الخامة', en: 'Compare the fabric' },
  'guide.step2Text': {
    ar: 'الوزن، العرض، المرونة، الشفافية والتشطيب؛ خمس قراءات تكفي لتجنّب المفاجآت.',
    en: 'Weight, width, stretch, opacity and finish — five readings are enough to avoid surprises.',
  },
  'guide.step3Title': { ar: 'احسبي الكمية', en: 'Estimate the quantity' },
  'guide.step3Text': {
    ar: 'أضيفي هامشاً للقص والخياطة، ثم اطلبي نصف متر كبداية وزيدي عند الحاجة.',
    en: 'Add a margin for cutting and sewing, then order half a meter to start and add more when needed.',
  },
  'guide.faqEyebrow': { ar: 'أسئلة تتكرر', en: 'Frequently asked' },
  'guide.faqTitle': { ar: 'أسئلة وإجابات سريعة', en: 'Quick questions and answers' },
  'guide.faqText': { ar: 'افتحي أي سؤال لتظهر الإجابة كاملة دون مغادرة الصفحة.', en: 'Open any question to see the full answer without leaving the page.' },
  'guide.faqLink': { ar: 'سؤال آخر؟ راسلينا', en: 'Another question? Message us' },
  'guide.faqPad': { ar: '٠{n}', en: '0{n}' },
  'guide.extraQ1Question': { ar: 'هل أحتاج إلى بطانة؟', en: 'Do I need a lining?' },
  'guide.extraQ1Answer': {
    ar: 'إذا ظهر حقل الشفافية بعبارة شفاف أو نصف شفاف فالأجدر استخدام بطانة. القطع الفاتحة والخفيفة تحتاج بطانة دائماً، بينما القماش غير الشفاف يكفي نفسه في الفساتين والعبايات.',
    en: 'If the opacity field says sheer or semi-sheer, a lining is the safer choice. Light, pale pieces always need one, while opaque fabric is enough on its own for dresses and abayas.',
  },
  'guide.extraQ2Question': { ar: 'كيف أختبر المرونة قبل الشراء؟', en: 'How do I test the stretch before buying?' },
  'guide.extraQ2Answer': {
    ar: 'اسحبي القماش برفق بين إصبعين في الاتجاهين: المطاطي يعود إلى مكانه فوراً، والمرونة الخفيفة تعود ببطء، وغير المطاطي يقاوم السحب أصلاً. تفاصيل كل منتج مكتوبة في حقل المرونة.',
    en: 'Pull the fabric gently between two fingers in both directions: stretchy fabric springs right back, light stretch returns slowly, and non-stretch fabric resists pulling altogether. Every product lists its stretch in the stretch field.',
  },
  'guide.extraQ3Question': { ar: 'كيف أعتني بالقماش المطرز؟', en: 'How do I care for embroidered fabric?' },
  'guide.extraQ3Answer': {
    ar: 'التطريز الحساس يفضّل التنظيف الجاف أو الغسيل اليدوي بماء فاتر مع قلب القطعة قبل التجفيف. تجنّبي المجفف وتعريض التطريز لخطافات الأثاث.',
    en: 'Delicate embroidery prefers dry cleaning or hand washing in lukewarm water, turned inside out before drying. Avoid the dryer and keep the embroidery away from furniture hooks.',
  },
  'guide.extraQ4Question': { ar: 'ما الفرق بين الكريب والتويل؟', en: 'What is the difference between crepe and twill?' },
  'guide.extraQ4Answer': {
    ar: 'الكريب سطحه مطفي بملمس حبيبي خفيف ويستقيم بسرعة، أما التويل فنسيجه قطري أوضح وأكثر ثباتاً في البنية، وهو أنسب للبناطيل والقطع الرسمية.',
    en: 'Crepe has a matte, lightly grained surface and drapes quickly, while twill has a clearer diagonal weave that holds its shape better — it suits trousers and formal pieces.',
  },
  'guide.extraQ5Question': { ar: 'كم متراً أحتاج لعمّة كاملة؟', en: 'How many meters do I need for a full abaya?' },
  'guide.extraQ5Answer': {
    ar: 'العباءة المستقيمة تحتاج عادة بين ٣ و٤ أمتار، وتزيد القطعة ذات الأكمام الواسعة أو التراكيب. أضيفي نصف متر إضافي للقص إن كان النمط مزدوجاً.',
    en: 'A straight abaya usually needs 3 to 4 meters, and wide sleeves or panels need more. Add half a meter for cutting if the pattern is one-way.',
  },
  'guide.tipsEyebrow': { ar: 'جدول عملي', en: 'A practical table' },
  'guide.tipsTitle': { ar: 'نصائح اختيار القماش حسب القطعة', en: 'Fabric-picking tips by garment' },
  'guide.tipsText': { ar: 'مرجع سريع تراجعينه قبل إضافة أي خامة إلى السلة.', en: 'A quick reference to check before adding any fabric to the cart.' },
  'guide.tipsChip': { ar: '٦ حالات شائعة', en: '6 common cases' },
  'guide.tipsAria': { ar: 'جدول نصائح اختيار القماش حسب القطعة', en: 'Fabric-picking tips by garment table' },
  'guide.tipsCaption': { ar: 'اخترِي صفّ قطعتك ثم اقرئي الخامة والوزن والملاحظة.', en: 'Find your garment row, then read the fabric, weight and note.' },
  'guide.thUse': { ar: 'القطعة', en: 'Garment' },
  'guide.thFabric': { ar: 'الخامة المقترحة', en: 'Suggested fabric' },
  'guide.thWeight': { ar: 'الوزن', en: 'Weight' },
  'guide.thTip': { ar: 'ملاحظة القياس', en: 'Measuring note' },
  'guide.tip1Use': { ar: 'فستان يومي', en: 'Everyday dress' },
  'guide.tip1Fabric': { ar: 'لينن قطن أو كريب سبانديكس', en: 'Linen-cotton or spandex crepe' },
  'guide.tip1Weight': { ar: 'خفيف إلى متوسط', en: 'Light to medium' },
  'guide.tip1Tip': { ar: 'اختر لوناً صلباً يتحمّل الغسيل المتكرر.', en: 'Pick a solid color that tolerates frequent washing.' },
  'guide.tip2Use': { ar: 'فستان سهرة', en: 'Evening dress' },
  'guide.tip2Fabric': { ar: 'ساتان أو تافتا مطرزة', en: 'Embroidered satin or taffeta' },
  'guide.tip2Weight': { ar: 'متوسط إلى ثقيل', en: 'Medium to heavy' },
  'guide.tip2Tip': { ar: 'لمعة هادئة وبطانة تمنح القماش سقوطاً أجمل.', en: 'A soft shine and a lining give the fabric a more elegant drape.' },
  'guide.tip3Use': { ar: 'عباءة أو برنوش', en: 'Abaya or burnous' },
  'guide.tip3Fabric': { ar: 'كريب مطرز أو جاكار', en: 'Embroidered crepe or jacquard' },
  'guide.tip3Weight': { ar: 'متوسط', en: 'Medium' },
  'guide.tip3Tip': { ar: 'راعي السقوط والطول قبل قصّ الأكمام.', en: 'Mind the drape and the length before cutting the sleeves.' },
  'guide.tip4Use': { ar: 'بناطيل وتنانير', en: 'Trousers and skirts' },
  'guide.tip4Fabric': { ar: 'تويل سبانديكس أو تويل قطني', en: 'Spandex twill or cotton twill' },
  'guide.tip4Weight': { ar: 'متوسط إلى ثقيل', en: 'Medium to heavy' },
  'guide.tip4Tip': { ar: 'مرونة باتجاه واحد تكفي لراحة الحركة.', en: 'One-way stretch is enough for comfortable movement.' },
  'guide.tip5Use': { ar: 'جاكيت شتوي', en: 'Winter jacket' },
  'guide.tip5Fabric': { ar: 'مخمل', en: 'Velvet' },
  'guide.tip5Weight': { ar: 'ثقيل', en: 'Heavy' },
  'guide.tip5Tip': { ar: 'الوبرة الكثيفة تحفظ الدفئة وتقلل التجعيد.', en: 'A dense pile keeps the warmth and reduces wrinkles.' },
  'guide.tip6Use': { ar: 'حفلة ومناسبة', en: 'Party or occasion' },
  'guide.tip6Fabric': { ar: 'ترتر هولوغرام', en: 'Hologram tulle' },
  'guide.tip6Weight': { ar: 'متوسط', en: 'Medium' },
  'guide.tip6Tip': { ar: 'قصّة بسيطة لأن البريق يضيف حجماً بصرياً.', en: 'Keep the cut simple, since the sparkle adds visual volume.' },
  'guide.tableHint': { ar: 'اسحبي الجدول أفقياً لعرض بقية الأعمدة.', en: 'Scroll the table horizontally to see the remaining columns.' },
  'guide.qualityEyebrow': { ar: 'فحص سريع', en: 'Quick check' },
  'guide.qualityTitle': { ar: 'علامات خامة جيدة', en: 'Signs of good quality fabric' },
  'guide.qualityText': { ar: 'ست نقاط تراجعينها على العينة قبل إتمام الطلب.', en: 'Six things to check on the sample before you place the order.' },
  'guide.check1': { ar: 'اللون متجانس من الحافة إلى الحافة دون تدرّج مفاجئ.', en: 'The color is even from edge to edge, with no sudden gradient.' },
  'guide.check2': { ar: 'الخيط لا ينفلت بسحب خفيف على الحافة المقصوصة.', en: 'The thread does not fray with a light pull on the cut edge.' },
  'guide.check3': { ar: 'الوزن يواجد مع الوصف: خفيف لا يعني رديئاً، وثقيل لا يعني مريحاً.', en: 'The weight matches the description: light does not mean poor, and heavy does not mean comfortable.' },
  'guide.check4': { ar: 'الطباعة أو التطريز متماسك من الوجهين.', en: 'The print or embroidery is consistent on both sides.' },
  'guide.check5': { ar: 'العطر غائب، لأن بقايا المعالجة الكيميائية تظهر لاحقاً.', en: 'There is no scent, since leftover chemical treatment shows up later.' },
  'guide.check6': { ar: 'العرض مطابق للمكتوب، ففرق السنتيمترات يغيّر حساب الكمية.', en: 'The width matches the listing, since a few centimeters change the quantity calculation.' },
  'guide.chipCut': { ar: 'قصّ بسيط', en: 'Simple cutting' },
  'guide.chipCare': { ar: 'عناية بالمطرز', en: 'Care for embroidery' },
  'guide.chipReply': { ar: 'الرد عبر الهاتف', en: 'Reply by phone' },
  'guide.chipConfirm': { ar: 'تأكيد قبل الشحن', en: 'Confirmation before shipping' },
  'guide.ctaStart': { ar: 'ابدئي من المعرض', en: 'Start from the showroom' },

  // ── Contact ──────────────────────────────────────────────────────────────
  'contact.crumbHome': { ar: 'الرئيسية', en: 'Home' },
  'contact.crumbCurrent': { ar: 'تواصلي معنا', en: 'Contact us' },
  'contact.eyebrow': { ar: 'نحن قريبون', en: 'We are close by' },
  'contact.method1Aria': { ar: 'افتحي نموذج التواصل في الموقع', en: 'Open the on-site contact form' },
  'contact.method1Title': { ar: 'نموذج التواصل', en: 'Contact form' },
  'contact.method1Text': { ar: 'أرسلي رسالتك من هذه الصفحة', en: 'Send your message from this page' },
  'contact.method2Aria': { ar: 'تتبّع حالة طلبك', en: 'Track your order status' },
  'contact.method2Title': { ar: 'تتبّع الطلب', en: 'Order tracking' },
  'contact.method2Text': { ar: 'اعرفي حالة طلبك برقم الطلب', en: 'Check your order status with the order number' },
  'contact.method3Aria': { ar: 'افتحي دليل الأقمشة', en: 'Open the fabric guide' },
  'contact.method3Title': { ar: 'دليل الأقمشة', en: 'Fabric guide' },
  'contact.method3Text': { ar: 'إجابات سريعة قبل الاستفسار', en: 'Quick answers before you ask' },
  'contact.hoursTitle': { ar: 'كيف نتواصل', en: 'How to reach us' },
  'contact.hours1Label': { ar: 'الاستفسار والطلب', en: 'Inquiries and orders' },
  'contact.hours1Value': { ar: 'عبر نموذج التواصل في الموقع', en: 'Through the on-site contact form' },
  'contact.hours2Label': { ar: 'تأكيد الطلب', en: 'Order confirmation' },
  'contact.hours2Value': { ar: 'نتواصل معك قبل الشحن', en: 'We contact you before shipping' },
  'contact.hours3Label': { ar: 'التوصيل', en: 'Delivery' },
  'contact.hours3Value': { ar: 'جميع المحافظات — ٥ آلاف دينار', en: 'All governorates — 5,000 IQD' },
  'contact.mapTitle': { ar: 'الموقع والعنوان', en: 'Location and address' },
  'contact.mapText': {
    ar: 'بغداد نستقبل الطلبات عبر المتجر أونلاين، ونرتّب موعد الاستلام بعد تأكيد الطلب. التوصيل يشمل جميع المحافظات العراقية، وللعنوان التفصيلي نرسله لك عند التأكيد.',
    en: 'In Baghdad we take orders through the online store and arrange a pickup time after confirmation. Delivery covers all Iraqi governorates, and we send you the detailed address when you confirm.',
  },
  'contact.formEyebrow': { ar: 'راسلينا', en: 'Message us' },
  'contact.formTitle': { ar: 'أرسلي رسالتك', en: 'Send your message' },
  'contact.formChip': { ar: 'الرد عبر الهاتف', en: 'Reply by phone' },
  'contact.nameLabel': { ar: 'الاسم', en: 'Name' },
  'contact.required': { ar: '(مطلوب)', en: '(required)' },
  'contact.namePlaceholder': { ar: 'كيف نناديك؟', en: 'What should we call you?' },
  'contact.phoneLabel': { ar: 'رقم الهاتف', en: 'Phone number' },
  'contact.messageLabel': { ar: 'الرسالة', en: 'Message' },
  'contact.messagePlaceholder': { ar: 'اكتبي سؤالك أو نوع الخامة التي تبحثين عنها', en: 'Write your question or the fabric type you are looking for' },
  'contact.errorNameShort': { ar: 'اكتبي اسمك من ٣ أحرف على الأقل', en: 'Enter your name with at least 3 letters' },
  'contact.errorNameScript': { ar: 'اكتبي اسمك بالحروف العربية أو اللاتينية', en: 'Enter your name in Arabic or Latin letters' },
  'contact.errorPhone': { ar: 'أدخلي رقم هاتف عراقي صحيحاً يبدأ بـ 07', en: 'Enter a valid Iraqi phone number starting with 07' },
  'contact.errorMessage': { ar: 'اكتبي رسالة من ١٠ أحرف على الأقل حتى نساعدك بدقة', en: 'Write a message of at least 10 letters so we can help accurately' },
  'contact.sending': { ar: 'جارٍ إرسال الرسالة', en: 'Sending your message' },
  'contact.send': { ar: 'إرسال الرسالة', en: 'Send message' },
  'contact.sent': {
    ar: 'وصلتنا رسالتك وسنتواصل معك عبر رقم الهاتف الذي أدخلتيه. وإن أحببتِ طلباً جديداً، أرسليه من صفحة إتمام الطلب.',
    en: 'We received your message and will contact you on the number you provided. If you would like to place a new order, send it from the checkout page.',
  },
  'contact.failed': { ar: 'تعذّر إرسال الرسالة الآن. حاولي مرة أخرى بعد قليل.', en: 'Your message could not be sent right now. Please try again in a moment.' },
  'contact.again': { ar: 'كتابة رسالة أخرى', en: 'Write another message' },
  'contact.browse': { ar: 'تصفحي الأقمشة', en: 'Browse fabrics' },
  'contact.footnote': { ar: 'نستخدم بياناتك للتواصل بشأن استفسارك فقط، ويمكنك مراجعة تفاصيل ذلك في', en: 'We use your details only to respond to your inquiry, and you can review the details in' },
  'contact.footnoteLink': { ar: 'سياسة الخصوصية', en: 'Privacy Policy' },
  'contact.emailSubject': { ar: 'رسالة من صفحة تواصل إيفا ستور', en: 'Message from the Eva Store contact page' },
  'contact.emailBody': { ar: 'مرحباً إيفا ستور،\nالاسم: {name}\nالهاتف: {phone}\n{message}', en: 'Hello Eva Store,\nName: {name}\nPhone: {phone}\n{message}' },

  // ── Policies ─────────────────────────────────────────────────────────────
  'policies.crumbHome': { ar: 'الرئيسية', en: 'Home' },
  'policies.crumbCurrent': { ar: 'السياسات', en: 'Policies' },
  'policies.eyebrow': { ar: 'واضحة منذ البداية', en: 'Clear from the start' },
  'policies.title': { ar: 'سياسات المتجر', en: 'Store policies' },
  'policies.intro': {
    ar: 'أربعة بنود تقرأينها مرة واحدة قبل إتمام الطلب: الاستخدام، الخصوصية، الشحن، والإرجاع. اضغطي على أي بند لفتحه.',
    en: 'Four sections to read once before you order: terms, privacy, shipping and returns. Tap any section to open it.',
  },
  'policies.navAria': { ar: 'الانتقال إلى بند من السياسات', en: 'Jump to a policy section' },
  'policies.numPad': { ar: '٠{n}', en: '0{n}' },
  'policies.cta': { ar: 'لديك سؤال آخر؟ تواصلي معنا', en: 'Have another question? Contact us' },
  'policies.termsTitle': { ar: 'شروط الاستخدام', en: 'Terms of use' },
  'policies.termsIntro': {
    ar: 'باستخدامك موقع إيفا ستور فإنك تقرّين بصحة البيانات التي تدخلينها وأن الهدف من الموقع هو طلب المنتجات المتاحة لدينا.',
    en: 'By using the Eva Store website you confirm that the details you enter are accurate and that the site is meant for ordering the products we offer.',
  },
  'policies.termsPoint1': { ar: 'الأسعار والمواصفات والألوان قابلة للتحديث، ويظهر السعر النهائي في مراجعة الطلب قبل التأكيد.', en: 'Prices, specs and colors may be updated, and the final price appears in the order review before you confirm.' },
  'policies.termsPoint2': { ar: 'كمية القماش تُحسب بالمتر ونصف المتر، والمخزون يُخصم عند تأكيد الطلب لا عند إضافته إلى السلة.', en: 'Fabric quantities are counted in meters and half meters, and stock is deducted when the order is confirmed, not when it is added to the cart.' },
  'policies.termsPoint3': { ar: 'يحق لنا التواصل معك للتأكيد عبر الهاتف قبل الشحن، ويُعد الطلب مؤكداً بعد هذا التواصل.', en: 'We may call you to confirm before shipping, and the order counts as confirmed after that call.' },
  'policies.termsPoint4': { ar: 'يُمنع إعادة بيع المنتجات أو استخدام صور المتجر دون إذن مكتوب.', en: 'Reselling our products or using the store images without written permission is not allowed.' },
  'policies.termsNote': { ar: 'بإرسال الطلب توافقين على هذه الشروط وعلى سياسة الإرجاع.', en: 'By sending the order you agree to these terms and to the return policy.' },
  'policies.privacyTitle': { ar: 'سياسة الخصوصية', en: 'Privacy policy' },
  'policies.privacyIntro': {
    ar: 'نستخدم البيانات التي تدخلينها لتنفيذ طلبك والتواصل معك بشأنه فقط، ونلتزم بعدم مشاركتها مع جهات غير ضرورية.',
    en: 'We use the details you enter only to fulfil your order and contact you about it, and we do not share them with unnecessary parties.',
  },
  'policies.privacyPoint1': { ar: 'نجمع الاسم ورقم الهاتف والعنوان وتفاصيل الطلب اللازمة للتنفيذ.', en: 'We collect the name, phone number, address and order details needed to fulfil the order.' },
  'policies.privacyPoint2': { ar: 'البريد الإلكتروني والملاحظات اختيارية ولا يشترط لإتمام الطلب.', en: 'Email and notes are optional and never required to complete an order.' },
  'policies.privacyPoint3': { ar: 'لا نحفظ بيانات الدفع، لأن الدفع يتم عند الاستلام في العراق.', en: 'We do not store payment details, since payment happens on delivery in Iraq.' },
  'policies.privacyPoint4': { ar: 'يمكنك طلب عرض بياناتك أو حذفها في أي وقت عبر نموذج التواصل في الموقع، وسنستجيب خلال أيام العمل.', en: 'You can request a copy or deletion of your data at any time through the on-site contact form, and we reply within business days.' },
  'policies.privacyNote': { ar: 'لن نرسل رسائل تسويقية دون موافقتك الصريحة.', en: 'We never send marketing messages without your explicit consent.' },
  'policies.shippingTitle': { ar: 'الشحن والتوصيل', en: 'Shipping and delivery' },
  'policies.shippingIntro': {
    ar: 'نجهّز الطلبات بعد التأكيد، ويظهر رقم الطلب في صفحة النجاح ويُرسل لك مع تحديثات الشحن.',
    en: 'We prepare orders after confirmation; the order number appears on the success page and is sent to you with shipping updates.',
  },
  'policies.shippingPoint1': { ar: 'التوصيل متاح إلى جميع المحافظات العراقية، ويعتمد الوقت على بعد المحافظة وحالة الطلب.', en: 'Delivery is available to all Iraqi governorates, and the timing depends on the distance and the order status.' },
  'policies.shippingPoint2': { ar: 'رسوم التوصيل ثابتة ٥ آلاف دينار، وتصبح مجانية للطلبات التي تتجاوز 50 الف دينار.', en: 'Delivery is a flat 5,000 IQD and becomes free for orders over 50,000 IQD.' },
  'policies.shippingPoint3': { ar: 'نجهّز الطلب بعد تأكيدك له، ونحدّث حالته في صفحة تتبّع الطلب عند خروجه للشحن.', en: 'We prepare the order after you confirm it, and its status is updated on the tracking page once it ships.' },
  'policies.shippingPoint4': { ar: 'نحدّثك عبر الهاتف عند خروج الطلب وعند تسليمه إلى مندوب الشحن.', en: 'We update you by phone when the order leaves and when it is handed to the courier.' },
  'policies.shippingNote': { ar: 'احتفظي برقم الطلب؛ فهو يكفي للاستفسار دون مشاركة بيانات إضافية.', en: 'Keep your order number — it is enough for any inquiry, with no extra details needed.' },
  'policies.returnsTitle': { ar: 'الإرجاع والتبديل', en: 'Returns and exchanges' },
  'policies.returnsIntro': {
    ar: 'نقبل الإرجاع أو التبديل إذا وصل القماش مختلفاً عن المواصفات المكتوبة أو حدث خطأ في التنفيذ، وتُحالة الحالة عبر نموذج التواصل في الموقع ونتفق معك على الحل المناسب.',
    en: 'We accept a return or exchange if the fabric arrives different from the written specs or a mistake was made while fulfilling it. Report the case through the on-site contact form and we agree on the right solution with you.',
  },
  'policies.returnsPoint1': { ar: 'يجب أن يبقى القماش بحالته الأصلية وغير مقصوص ولا مستعمل.', en: 'The fabric must stay in its original condition — uncut and unused.' },
  'policies.returnsPoint2': { ar: 'الأقمشة المقصوصة حسب الطلب أو المقطوعة حسب القياس غير قابلة للإرجاع.', en: 'Fabrics cut to order or cut to size cannot be returned.' },
  'policies.returnsPoint3': { ar: 'في حال ثبوت خطأ منّا نتحمل رسوم الإرجاع ونشحن البديل على حسابنا.', en: 'If the mistake is ours, we cover the return fee and ship the replacement at our cost.' },
  'policies.returnsPoint4': { ar: 'التواصل الأول يتم عبر نموذج التواصل في الموقع مع إرفاق صورة للقماش ورقم الطلب.', en: 'Start by using the on-site contact form and attach a photo of the fabric and the order number.' },
  'policies.returnsNote': { ar: 'اللون المطابق للصور مضمون، والاختلاف البسيط تحت الإضاءة لا يُعد عيباً.', en: 'The color matches the photos; a slight shift under lighting is not considered a defect.' },

  // ── Order tracking & status ──────────────────────────────────────────────
  'track.crumbHome': { ar: 'الرئيسية', en: 'Home' },
  'track.crumbCurrent': { ar: 'تتبّع الطلب', en: 'Track order' },
  'track.eyebrow': { ar: 'حالة الطلب من المتجر مباشرة', en: 'Live order status from the store' },
  'track.title': { ar: 'تتبّع الطلب', en: 'Track your order' },
  'track.intro': {
    ar: 'أدخلي رقم الطلب الذي وصلك بعد التأكيد لعرض حالته الحالية من المتجر، مع الطلبات المحفوظة على هذا الجهاز.',
    en: 'Enter the order number you received after confirmation to see its current status from the store, along with the orders saved on this device.',
  },
  'track.inputLabel': { ar: 'رقم الطلب', en: 'Order number' },
  'track.placeholder': { ar: 'مثال: EVA-1024', en: 'e.g. EVA-1024' },
  'track.submit': { ar: 'عرض الحالة', en: 'Show status' },
  'track.errorEmpty': { ar: 'أدخلي رقم الطلب الذي وصلك بعد التأكيد', en: 'Enter the order number you received after confirmation' },
  'track.loading': { ar: 'جارٍ التحقق من حالة الطلب...', en: 'Checking the order status...' },
  'track.searchedFor': { ar: 'بحثتِ عن:', en: 'You searched for:' },
  'track.refresh': { ar: 'تحديث الحالة', en: 'Refresh status' },
  'track.synced': { ar: 'مزامنة مع المتجر ✓', en: 'Synced with the store ✓' },
  'track.remoteError': { ar: 'تعذّر الاتصال للتحقق من الطلب {order}', en: 'Could not connect to check order {order}' },
  'track.notFound': { ar: 'لم نجد طلباً بالرقم {order}', en: 'We could not find an order with the number {order}' },
  'track.notFoundHint': {
    ar: 'تأكدي من الرقم كما وصل في رسالة التأكيد، أو اختاري أحد الطلبات المحفوظة على هذا الجهاز.',
    en: 'Check the number as it appeared in your confirmation message, or pick one of the orders saved on this device.',
  },
  'track.emptyTitle': { ar: 'لا توجد طلبات محفوظة على هذا الجهاز بعد', en: 'No orders saved on this device yet' },
  'track.emptyText': {
    ar: 'عند إتمام أول طلب يُحفظ رقم الطلب على هذا الجهاز لتتبعي حالته بدون تسجيل دخول.',
    en: 'After your first order, the order number is saved on this device so you can track it without signing in.',
  },
  'track.browse': { ar: 'تصفحي الأقمشة', en: 'Browse fabrics' },
  'track.contact': { ar: 'تواصلي معنا', en: 'Contact us' },
  'track.localOrders': { ar: 'طلبات محفوظة على هذا الجهاز:', en: 'Orders saved on this device:' },
  'track.askButton': { ar: 'اسألينا عبر نموذج التواصل في الموقع', en: 'Ask us via the on-site contact form' },
  'track.panelAria': { ar: 'حالة الطلب', en: 'Order status' },
  'track.statusTitle': { ar: 'حالة الطلب', en: 'Order status' },
  'track.lastUpdate': { ar: 'آخر تحديث', en: 'Last update' },
  'track.cancelled': { ar: 'تم إلغاء الطلب', en: 'The order was cancelled' },
  'track.registeredAt': { ar: 'تاريخ التسجيل', en: 'Registered on' },
  'track.step1': { ar: 'تم استلام الطلب', en: 'Order received' },
  'track.step2': { ar: 'قيد المراجعة', en: 'Under review' },
  'track.step3': { ar: 'جاهز للشحن', en: 'Ready to ship' },
  'track.step4': { ar: 'في الطريق إليك', en: 'On its way to you' },
  'track.step5': { ar: 'تم التوصيل', en: 'Delivered' },
  'track.stepDone': { ar: 'مكتمل', en: 'Done' },
  'track.stepCurrent': { ar: 'الوضع الحالي', en: 'Current step' },
  'track.stepLater': { ar: 'لاحقاً', en: 'Later' },
  'track.itemsTitle': { ar: 'عناصر الطلب', en: 'Order items' },
  'track.total': { ar: 'الإجمالي', en: 'Total' },
  'track.statusNew': { ar: 'جديد', en: 'New' },
  'track.statusContacted': { ar: 'تم التواصل', en: 'Contacted' },
  'track.statusShipped': { ar: 'تم الشحن', en: 'Shipped' },
  'track.statusDone': { ar: 'مكتمل', en: 'Completed' },
  'track.statusInTransit': { ar: 'قيد التوصيل', en: 'Out for delivery' },

  // ── Order confirmation ───────────────────────────────────────────────────
  'confirm.emptyTitle': { ar: 'لا يوجد طلب لعرضه', en: 'No order to show' },
  'confirm.emptyText': {
    ar: 'لم يصلنا رقم طلب في هذا الرابط. افتحي رسالة التأكيد التي وصلك، أو ابحثي عن طلبك برقم الطلب.',
    en: 'No order number reached us from this link. Open the confirmation message you received, or look up your order by its number.',
  },
  'confirm.track': { ar: 'تتبّع الطلب', en: 'Track order' },
  'confirm.ask': { ar: 'راسلينا عبر الموقع', en: 'Message us on the site' },
  'confirm.eyebrow': { ar: 'تم استلام طلبك', en: 'We received your order' },
  'confirm.title': { ar: 'شكراً لاختيارك إيفا.', en: 'Thank you for choosing Eva.' },
  'confirm.text': {
    ar: 'سنراجع تفاصيل طلبك ونتواصل معك لتأكيد التوصيل. احتفظي برقم الطلب لمتابعة حالته في أي وقت.',
    en: 'We will review your order and contact you to confirm delivery. Keep the order number to check its status at any time.',
  },
  'confirm.orderNumber': { ar: 'رقم الطلب', en: 'Order number' },
  'confirm.copy': { ar: 'نسخ رقم الطلب', en: 'Copy order number' },
  'confirm.copied': { ar: 'تم النسخ', en: 'Copied' },
  'confirm.continue': { ar: 'متابعة التسوق', en: 'Continue shopping' },
  'confirm.trackStatus': { ar: 'تتبّع حالة الطلب', en: 'Track order status' },
  'confirm.trust': {
    ar: 'التوصيل مجاني للطلبات التي تتجاوز 50 الف دينار، ويمكنك متابعة الحالة في صفحة تتبّع الطلب.',
    en: 'Delivery is free for orders over 50,000 IQD, and you can follow the status on the order tracking page.',
  },

  // ── Not found ────────────────────────────────────────────────────────────
  'nf.eyebrow': { ar: 'الصفحة غير موجودة', en: 'Page not found' },
  'nf.title': { ar: 'هذا الرابط لم يعد متاحاً', en: 'This link is no longer available' },
  'nf.text': {
    ar: 'ربما تغيّر العنوان أو حُذفت الصفحة. لا بأس: يمكنك العودة إلى الرئيسية أو متابعة تصفّح الأقمشة واختيار خامة جديدة.',
    en: 'The address may have changed or the page was removed. No problem: go back home or keep browsing the fabrics and pick a new one.',
  },
  'nf.home': { ar: 'العودة إلى الرئيسية', en: 'Back to home' },
  'nf.browse': { ar: 'تصفحي الأقمشة', en: 'Browse fabrics' },
  'nf.guide': { ar: 'دليل الأقمشة', en: 'Fabric guide' },
  'nf.about': { ar: 'من نحن', en: 'About us' },
  'nf.contact': { ar: 'تواصلي معنا', en: 'Contact us' },
  'nf.tracking': { ar: 'تتبّع الطلب', en: 'Track order' },
  'nf.favorites': { ar: 'المفضلة', en: 'Favorites' },
  'nf.policies': { ar: 'السياسات', en: 'Policies' },
}

/** English copy mirroring `guideQuestions` from `@/lib/fallback-data`. */
export const guideFaqsEn: ProductFaq[] = [
  {
    question: 'How do I choose the right fabric?',
    answer: 'Start with the use: everyday dresses need a light, comfortable fabric, while occasion wear may call for weight, structure and shine. Check the stretch, opacity and width before you buy.',
  },
  {
    question: 'What is the difference between stretchy and non-stretchy?',
    answer: 'Stretchy fabric contains elastane or spandex, so it stretches and returns to shape. Non-stretchy fabric holds its structure better and suits pieces with a clear silhouette. Store labels follow the actual stretch of the design.',
  },
  {
    question: 'How do I know the right width?',
    answer: 'Width is the fabric measurement from edge to edge, and it is listed in every product spec. The wider the fabric, the less you need for a single garment.',
  },
  {
    question: 'How much fabric do I need?',
    answer: 'A simple garment usually needs 2 to 2.5 meters, and an abaya 3 to 4 meters. Add a small margin for cutting and sewing, and you can order from half a meter.',
  },
  {
    question: 'How do I read the color description?',
    answer: 'Photos are a visual sample of the fabric. Compare the color with your lighting and with similar pieces, and contact us if the color is critical to your project.',
  },
]

/** English copy mirroring `quickGuideAnswers` from `@/lib/fallback-data`. */
export const quickGuideAnswersEn: { question: string; answers: string[] }[] = [
  {
    question: 'How many meters do I need for a dress?',
    answers: [
      'Simple sleeveless dress: between 2 and 2.5 meters.',
      'Dress with sleeves or a lining: 3 meters is a safe start.',
      'Wide 150 cm fabric cuts the need by about half a meter.',
    ],
  },
  {
    question: 'What is the difference between crepe and twill?',
    answers: [
      'Crepe has a matte surface with a light grain and drapes quickly.',
      'Twill has a clearer diagonal weave and holds its shape, so it suits trousers better.',
      'For everyday wear crepe is calmer; for formal wear twill looks cleaner.',
    ],
  },
  {
    question: 'Do I need a lining?',
    answers: [
      'Yes, if the opacity field says “sheer” or “semi-sheer”.',
      'Light, pale fabrics always need a lining.',
      'Velvet and heavy crepe do not need one.',
    ],
  },
  {
    question: 'How do I test the stretch before buying?',
    answers: [
      'Pull the fabric between two fingers: stretchy fabric springs right back.',
      'Light stretch returns slowly, and non-stretch fabric resists pulling.',
      'Check the stretch field on the product page before confirming the order.',
    ],
  },
  {
    question: 'How many meters do I need for an abaya?',
    answers: [
      'Straight abaya: between 3 and 4 meters.',
      'Wide sleeves or panels: add half a meter.',
      'Always allow a 10 cm cutting margin before confirming the quantity.',
    ],
  },
  {
    question: 'How do I care for embroidered fabric?',
    answers: [
      'Dry clean or hand wash in lukewarm water, turning the piece inside out.',
      'Avoid the dryer and furniture hooks to protect the embroidery.',
      'Dry it flat, away from direct sunlight.',
    ],
  },
]
