import type { StringEntry } from '@/lib/i18n'

/** UI strings for this area — every entry needs both `ar` and `en`. */
export const productStrings: Record<string, StringEntry> = {
  // — ProductPage —
  'pd.breadcrumbHome': { ar: 'الرئيسية', en: 'Home' },
  'pd.breadcrumbFabrics': { ar: 'الأقمشة', en: 'Fabrics' },
  'pd.galleryAria': { ar: 'معرض صور {name}', en: '{name} photo gallery' },
  'pd.videoAria': { ar: '{name} — فيديو', en: '{name} — video' },
  'pd.unmute': { ar: 'اضغطي لتشغيل الصوت', en: 'Tap to unmute' },
  'pd.photoAlt': { ar: '{name} - صورة {n}', en: '{name} - photo {n}' },
  'pd.zoom': { ar: 'تكبير الصورة', en: 'Zoom in' },
  'pd.next': { ar: 'التالي', en: 'Next' },
  'pd.nextPhoto': { ar: 'الصورة التالية', en: 'Next photo' },
  'pd.prev': { ar: 'السابق', en: 'Previous' },
  'pd.prevPhoto': { ar: 'الصورة السابقة', en: 'Previous photo' },
  'pd.thumbVideo': { ar: 'عرض الفيديو', en: 'Play video' },
  'pd.thumbPhoto': { ar: 'عرض الصورة {n}', en: 'Show photo {n}' },
  'pd.wishRemove': { ar: 'إزالة من المفضلة', en: 'Remove from favorites' },
  'pd.wishAdd': { ar: 'إضافة إلى المفضلة', en: 'Add to favorites' },
  'pd.pricePerMeter': { ar: 'السعر للمتر الواحد', en: 'Price per meter' },
  'pd.qtyHeading': { ar: 'الكمية المطلوبة', en: 'Requested quantity' },
  'pd.qtyHint': { ar: 'يمكن الطلب بنصف متر كحد أدنى', en: 'Half a meter is the minimum order' },
  'pd.availability': { ar: 'التوفّر يُؤكَّد عند الطلب', en: 'Availability is confirmed at order time' },
  'pd.decreaseHalf': { ar: 'إنقاص نصف متر', en: 'Decrease by half a meter' },
  'pd.increaseHalf': { ar: 'زيادة نصف متر', en: 'Increase by half a meter' },
  'pd.metersInputAria': { ar: 'إدخال عدد الأمتار مباشرة', en: 'Enter meters directly' },
  'pd.unitMeters': { ar: 'متر', en: 'meter' },
  'pd.lineTotal': { ar: 'الإجمالي — {meters} × {price} للمتر', en: 'Total — {meters} × {price} per meter' },
  'pd.unavailable': { ar: 'غير متوفر حالياً', en: 'Currently unavailable' },
  'pd.addCart': { ar: 'أضيفي إلى السلة', en: 'Add to cart' },
  'pd.addedToast': { ar: 'أضيف {meters} من {name} إلى السلة', en: 'Added {meters} of {name} to the cart' },
  'pd.checkoutNow': { ar: 'إتمام الطلب الآن', en: 'Checkout now' },
  'pd.perkDelivery': { ar: 'توصيل آمن للعراق', en: 'Safe delivery across Iraq' },
  'pd.perkOneBox': { ar: 'الطلب بمربع واحد', en: 'One-box ordering' },
  'pd.specsTitle': { ar: 'مواصفات القماش', en: 'Fabric specifications' },
  'pd.faqTitle': { ar: 'أسئلة حول الخامة', en: 'Questions about this fabric' },
  'pd.shippingTitle': { ar: 'الشحن والإرجاع', en: 'Shipping & returns' },
  'pd.shippingText': {
    ar: 'نجهز الطلبات بعد التأكيد، ونرتب الشحن بحسب المحافظة. لأي استفسار عن الإرجاع أو تبديل اللون راسلنا عبر نموذج التواصل في الموقع.',
    en: 'We prepare orders after confirmation and arrange shipping by governorate. For any return or color-exchange question, reach us through the contact form on the site.',
  },
  'pd.spec.composition': { ar: 'الخامة', en: 'Composition' },
  'pd.spec.width': { ar: 'العرض', en: 'Width' },
  'pd.spec.weight': { ar: 'السماكة', en: 'Weight' },
  'pd.spec.stretch': { ar: 'التمدد', en: 'Stretch' },
  'pd.spec.opacity': { ar: 'الشفافية', en: 'Sheerness' },
  'pd.spec.finish': { ar: 'التشطيب', en: 'Finish' },
  'pd.spec.use': { ar: 'الاستخدام', en: 'Use' },
  'pd.spec.care': { ar: 'العناية', en: 'Care' },
  'pd.faqQ1': { ar: 'هل يمكن طلب أكثر من نصف متر؟', en: 'Can I order more than half a meter?' },
  'pd.faqA1': { ar: 'يمكن طلب الأقمشة بنصف متر كحد أدنى.', en: 'Fabrics can be ordered from half a meter as a minimum.' },
  'pd.relatedEyebrow': { ar: 'اختيارات قريبة', en: 'You may also like' },
  'pd.relatedTitle': { ar: 'أقمشة ذات صلة', en: 'Related fabrics' },
  'pd.relatedNavAria': { ar: 'تصفّح الأقمشة ذات الصلة', en: 'Browse related fabrics' },
  'pd.relatedPrevAria': { ar: 'عرض الأقمشة السابقة', en: 'Show previous fabrics' },
  'pd.relatedNextAria': { ar: 'عرض الأقمشة التالية', en: 'Show next fabrics' },
  'pd.viewCategory': { ar: 'عرض الفئة', en: 'View category' },
  'pd.comparePrice': { ar: 'السعر / م', en: 'Price / m' },
  'pd.compareEyebrow': { ar: 'مقارنة سريعة', en: 'Quick comparison' },
  'pd.compareTitle': { ar: 'قارني هذه الخامة', en: 'Compare this fabric' },
  'pd.compareTableAria': { ar: 'جدول مقارنة الأقمشة', en: 'Fabric comparison table' },
  'pd.compareSpec': { ar: 'المواصفة', en: 'Specification' },
  'pd.checkout': { ar: 'إتمام الطلب', en: 'Checkout' },
  'pd.addLength': { ar: 'أضيفي {meters}', en: 'Add {meters}' },
  'pd.zoomTitle': { ar: 'صورة {name}', en: '{name} photo' },
  'pd.closeImage': { ar: 'إغلاق الصورة', en: 'Close image' },
  'pd.zoomAlt': { ar: '{name} مكبرة', en: '{name} enlarged' },
  'pd.missingTitle': { ar: 'هذه العينة غير موجودة', en: 'This sample was not found' },
  'pd.missingText': { ar: 'ربما تغير الرابط أو لم تعد القطعة معروضة.', en: 'The link may have changed, or the piece is no longer listed.' },
  'pd.backToFabrics': { ar: 'العودة إلى الأقمشة', en: 'Back to fabrics' },

  // — CartPage —
  'cart.updated': { ar: 'تم تحديث كمية {name} إلى {meters}', en: 'Updated {name} quantity to {meters}' },
  'cart.removed': { ar: 'تم حذف {name} من السلة', en: 'Removed {name} from the cart' },
  'cart.emptyTitle': { ar: 'السلة هادئة الآن', en: 'Your cart is quiet for now' },
  'cart.emptyText': {
    ar: 'أضيفي قماشاً يعجبك، وستظهر تفاصيله هنا مع السعر لكل متر وإمكانية تعديل الكمية بنصف متر.',
    en: 'Add a fabric you love and its details will appear here, with the price per meter and half-meter quantity controls.',
  },
  'cart.browse': { ar: 'تصفحي الأقمشة', en: 'Browse fabrics' },
  'cart.home': { ar: 'الرئيسية', en: 'Home' },
  'cart.crumb': { ar: 'السلة', en: 'Cart' },
  'cart.eyebrow': { ar: 'اختياراتك', en: 'Your picks' },
  'cart.title': { ar: 'سلة التسوق', en: 'Shopping cart' },
  'cart.inCart': { ar: '{meters} في السلة', en: '{meters} in the cart' },
  'cart.continue': { ar: 'متابعة التسوق', en: 'Continue shopping' },
  'cart.itemsAria': { ar: 'عناصر السلة', en: 'Cart items' },
  'cart.perMeter': { ar: 'متر', en: 'meter' },
  'cart.edit': { ar: 'تعديل', en: 'Edit' },
  'cart.removeAria': { ar: 'حذف {name} من السلة', en: 'Remove {name} from the cart' },
  'cart.decreaseAria': { ar: 'إنقاص كمية {name}', en: 'Decrease {name} quantity' },
  'cart.qtyAria': { ar: 'كمية {name}', en: 'Quantity of {name}' },
  'cart.increaseAria': { ar: 'زيادة كمية {name}', en: 'Increase {name} quantity' },
  'cart.summary': { ar: 'ملخص الطلب', en: 'Order summary' },
  'cart.freeAt': { ar: 'التوصيل المجاني عند {amount}', en: 'Free delivery at {amount}' },
  'cart.remaining': { ar: '{amount} متبقية', en: '{amount} to go' },
  'cart.progressAria': { ar: 'التقدم نحو التوصيل المجاني', en: 'Progress toward free delivery' },
  'cart.freeUnlocked': { ar: 'حصلتِ على توصيل مجاني لهذا الطلب', en: 'You have free delivery on this order' },
  'cart.subtotal': { ar: 'المجموع الفرعي', en: 'Subtotal' },
  'cart.delivery': { ar: 'التوصيل', en: 'Delivery' },
  'cart.estimated': { ar: '(تقديري)', en: '(estimated)' },
  'cart.free': { ar: 'مجاناً', en: 'Free' },
  'cart.total': { ar: 'الإجمالي', en: 'Total' },
  'cart.checkout': { ar: 'إتمام الطلب', en: 'Checkout' },
  'cart.summaryNote': {
    ar: 'يُحتسب التوصيل حسب المحافظة، ويمكنك مراجعة كل التفاصيل قبل التأكيد النهائي.',
    en: 'Delivery is calculated by governorate, and you can review every detail before the final confirmation.',
  },
  'cart.savedNote': { ar: 'السلة محفوظة على هذا الجهاز', en: 'Your cart is saved on this device' },

  // — CheckoutPage —
  'co.emptyTitle': { ar: 'لا توجد عناصر لإتمام الطلب', en: 'Nothing to check out yet' },
  'co.emptyText': { ar: 'أضيفي قماشاً إلى السلة أولاً، ثم املئي مربع الطلب بخطوة واحدة.', en: 'Add a fabric to your cart first, then fill in the order box in one step.' },
  'co.backToFabrics': { ar: 'العودة إلى الأقمشة', en: 'Back to fabrics' },
  'co.errName': { ar: 'اكتبي الاسم الكامل (3 أحرف على الأقل)', en: 'Enter your full name (3 characters minimum)' },
  'co.errPhone': { ar: 'أدخلي رقم هاتف عراقي صحيحاً يبدأ بـ 07 أو +964', en: 'Enter a valid Iraqi phone number starting with 07 or +964' },
  'co.errGovernorate': { ar: 'اختاري المحافظة من القائمة', en: 'Select a governorate from the list' },
  'co.errDistrict': { ar: 'أدخلي المنطقة أو القضاء', en: 'Enter the district or sub-district' },
  'co.errAddress': { ar: 'أدخلي العنوان: المحلة والشارع ورقم المنزل', en: 'Enter your address: neighborhood, street, and house number' },
  'co.errLandmark': { ar: 'أدخلي أقرب نقطة دالة تساعدنا في الوصول', en: 'Enter a nearby landmark to help us find you' },
  'co.errEmail': { ar: 'البريد الإلكتروني غير صحيح', en: 'The email address is not valid' },
  'co.errConsent': { ar: 'شدّي الموافقة على شروط الاستخدام وسياسة الخصوصية لتأكيد الطلب', en: 'Tick the agreement to the terms of use and privacy policy to confirm your order' },
  'co.errSummary': { ar: 'يرجى إكمال الحقول: {list}', en: 'Please complete the fields: {list}' },
  'co.orderSuccess': { ar: 'تم استلام طلبك بنجاح. رقم طلبك {number}', en: 'Your order was received. Your order number is {number}' },
  'co.connectionError': { ar: 'تأكدي من الاتصال فقط', en: 'Please check your connection' },
  'co.connectionHold': { ar: 'تأكدي من الاتصال فقط. طلبك محفوظ لدينا وسيُرسل تلقائياً عند عودة الاتصال.', en: 'Please check your connection. Your order is saved with us and will be sent automatically once you are back online.' },
  'co.sending': { ar: 'جارٍ إرسال الطلب إلى المتجر...', en: 'Sending your order to the store...' },
  'co.serverStatus': { ar: 'الخادم أعاد الرد رقم {status}', en: 'The server returned status {status}' },
  'co.timeout': { ar: 'انتهت مهلة الاتصال', en: 'The connection timed out' },
  'co.noConnection': { ar: 'تعذر الاتصال', en: 'Could not connect' },
  'co.crumbCart': { ar: 'السلة', en: 'Cart' },
  'co.crumbCheckout': { ar: 'إتمام الطلب', en: 'Checkout' },
  'co.eyebrow': { ar: 'مربع واحد فقط', en: 'Just one box' },
  'co.title': { ar: 'أكمل طلبك', en: 'Complete your order' },
  'co.backToCart': { ar: 'العودة للسلة', en: 'Back to cart' },
  'co.trustNoAccount': { ar: 'بدون تسجيل أو كلمة مرور', en: 'No sign-up or password' },
  'co.trustCod': { ar: 'الدفع عند الاستلام', en: 'Cash on delivery' },
  'co.trustRecorded': { ar: 'الطلب يُسجَّل فوراً في المتجر', en: 'Your order is recorded in the store instantly' },
  'co.deliveryInfo': { ar: 'معلومات التوصيل', en: 'Delivery information' },
  'co.deliveryIntro': { ar: 'اسمك، عنوانك وأقرب نقطة دالة — كل ما نحتاجه في مربع واحد، ثم زر تأكيد واحد.', en: 'Your name, address, and nearest landmark — everything we need in one box, then a single confirm button.' },
  'co.labelName': { ar: 'الاسم الكامل', en: 'Full name' },
  'co.phName': { ar: 'مثال: سارة أحمد', en: 'e.g. Sara Ahmed' },
  'co.labelPhone': { ar: 'رقم الهاتف', en: 'Phone number' },
  'co.labelGovernorate': { ar: 'المحافظة', en: 'Governorate' },
  'co.phGovernorate': { ar: 'اختاري المحافظة', en: 'Select a governorate' },
  'co.labelDistrict': { ar: 'المنطقة أو القضاء', en: 'District or sub-district' },
  'co.phDistrict': { ar: 'مثال: الكرادة داخل', en: 'e.g. Karrada Dakhil' },
  'co.labelAddress': { ar: 'العنوان بالتفصيل', en: 'Full address' },
  'co.phAddress': { ar: 'المحلة، الشارع، رقم المنزل والدور', en: 'Neighborhood, street, house and floor number' },
  'co.labelLandmark': { ar: 'أقرب نقطة دالة', en: 'Nearest landmark' },
  'co.phLandmark': { ar: 'مثال: جامع النور، صيدلية الشفاء، جسر المعلّق', en: 'e.g. Al-Noor Mosque, Al-Shifa Pharmacy, Ma’lak Bridge' },
  'co.hintLandmark': { ar: 'علامة قريبة تكفي للوصول أسرع عند التوصيل.', en: 'A nearby landmark is enough for faster delivery.' },
  'co.labelNotes': { ar: 'ملاحظات للتوصيل', en: 'Delivery notes' },
  'co.optional': { ar: '(اختياري)', en: '(optional)' },
  'co.phNotes': { ar: 'وقت مناسب للتوصيل أو تعليمات إضافية', en: 'A good time to deliver or extra instructions' },
  'co.labelEmail': { ar: 'البريد الإلكتروني', en: 'Email' },
  'co.serverErrorBody': { ar: 'طلبك محفوظ عندنا وسيُسجَّل تلقائياً بمجرد عودة الاتصال، ولا داعي لإعادة كتابة أي شيء.', en: 'Your order is saved with us and will be recorded automatically as soon as you are back online — there is no need to retype anything.' },
  'co.savedOrderNumber': { ar: 'رقم طلبك المحفوظ: ', en: 'Your saved order number: ' },
  'co.retryNow': { ar: 'إعادة المحاولة الآن', en: 'Try again now' },
  'co.totalWithDelivery': { ar: 'الإجمالي شامل التوصيل', en: 'Total including delivery' },
  'co.pieceOne': { ar: 'قطعة', en: 'item' },
  'co.pieceMany': { ar: 'قطع', en: 'items' },
  'co.deliveryFee': { ar: 'توصيل {price}', en: 'Delivery {price}' },
  'co.deliveryFree': { ar: 'توصيل مجاني', en: 'Free delivery' },
  'co.consentTitle': { ar: 'أوافق على شروط الاستخدام وسياسة الخصوصية', en: 'I agree to the terms of use and privacy policy' },
  'co.consentHelp': { ar: 'نستخدم بياناتك لتجهيز الطلب والتواصل معك فقط، ولا نشاركها مع أي جهة أخرى.', en: 'We use your details only to prepare your order and contact you — never shared with anyone else.' },
  'co.linkTerms': { ar: 'الشروط', en: 'Terms' },
  'co.linkPrivacy': { ar: 'الخصوصية', en: 'Privacy' },
  'co.submitLoading': { ar: 'جارٍ إرسال الطلب', en: 'Sending your order' },
  'co.submit': { ar: 'تأكيد الطلب', en: 'Place order' },
  'co.summary': { ar: 'ملخص طلبك', en: 'Your order summary' },
  'co.subtotal': { ar: 'المجموع الفرعي', en: 'Subtotal' },
  'co.delivery': { ar: 'التوصيل', en: 'Delivery' },
  'co.estimated': { ar: '(تقديري)', en: '(estimated)' },
  'co.free': { ar: 'مجاناً', en: 'Free' },
  'co.total': { ar: 'الإجمالي', en: 'Total' },
  'co.notSentNote': { ar: 'لن يُرسل الطلب إلا بعد الضغط على تأكيد', en: 'The order is only sent after you tap confirm' },
}

/** English display names for `product.type` (content stays Arabic in AR mode). */
export const typeLabelsEn: Record<string, string> = {
  plain: 'Plain',
  patterned: 'Printed',
  stretch: 'Stretchy',
  embroidered: 'Embroidered',
  sequined: 'Sequined',
  style: 'Style',
  harvard: 'Harvard',
  'سادة': 'Plain',
  'مزخرف': 'Printed',
  'مطاطي': 'Stretchy',
  'مطرز': 'Embroidered',
  'ترتر': 'Sequined',
  'ستايل': 'Style',
  'هارفرد': 'Harvard',
}
