import type { Category, Product, ProductColor, ProductFaq, SiteRoute } from '@/types'

const media = (name: string): string => `media/${name}.svg`

export const partners: string[] = ['VEIN', 'TURKART', 'الامل الشريف', 'البركة', 'الياقوت والمرجان', 'انجيكو', 'TAHOE', 'JUSTER']

const color = (id: string, name: string, hex: string, stock = 40): ProductColor => ({
  id,
  name,
  hex,
  available: stock > 0,
  stock,
})

const faqs = (stock: string, install: string, unit: string, care: string): ProductFaq[] => [
  { question: 'هل المنتج متوفر حالياً؟', answer: stock },
  { question: 'كيف تتم التوريد والتركيب؟', answer: install },
  { question: 'ما وحدة البيع والكمية المطلوبة؟', answer: unit },
  { question: 'كيف يتم حفظ المنتج؟', answer: care },
]

export const fallbackCategories: Category[] = [
  {
    id: 'structural',
    slug: 'structural',
    name: 'مواد إنشائية',
    description: 'إسمنت وحديد وطوب ومواد بناء',
    image: media('brick'),
    accent: '#0E6B45',
  },
  {
    id: 'tiles',
    slug: 'tiles',
    name: 'بلاط وسيراميك',
    description: 'أرضيات وحوائط بمقاسات متنوعة',
    image: media('tile-floor'),
    accent: '#1F5C87',
  },
  {
    id: 'sanitary',
    slug: 'sanitary',
    name: 'مواد صحية',
    description: 'أحواض ومراحيض وخزانات وخلاطات',
    image: media('basin'),
    accent: '#2F7D5A',
  },
  {
    id: 'paints',
    slug: 'paints',
    name: 'أصباغ ومعاجين',
    description: 'دهانات داخلية وخارجية وبلاستر',
    image: media('paint-matte'),
    accent: '#C05A11',
  },
  {
    id: 'tools',
    slug: 'tools',
    name: 'أدوات ولوازم',
    description: 'أدوات تركيب ومستلزمات الموقع',
    image: media('roller'),
    accent: '#4A5A52',
  },
]

export const fallbackProducts: Product[] = [
  {
    id: 'p1',
    slug: 'portland-cement-42',
    name: 'إسمنت عادي — كيس 50 كغ',
    type: 'مواد إنشائية',
    categoryId: 'structural',
    description: 'إسمنت بورتلاندي للاعمال العامة: خرسانات، طوب، معاجين ولياسات. يُورّد بالكيس مع إمكانية توزيع الكميات على مراحل حسب جدول الموقع.',
    price: 14000,
    image: media('cement'),
    images: [media('cement'), media('brick'), media('rebar')],
    colors: [
      color('grey', 'رمادي إسمنتي', '#9aa0a6', 260),
      color('off-white', 'رمادي فاتح', '#c3c7c4', 80),
    ],
    specs: {
      material: 'بورتلاندي إسمنتي',
      size: 'كيس 50 كغ',
      weight: '50 كغ',
      install: 'يُخلط بالماء حسب نسبة الخلط المطلوبة للعمل',
      finish: 'رمادي مطفي',
      supply: 'متوفر من المخزن للطلبات الفردية والمشاريع',
      use: 'خرسانات، طوب، معاجين ولياسات',
      care: 'يُحفظ في مكان جاف بعيداً عن الرطوبة وفوق قاعدة خشبية',
    },
    faqs: faqs(
      'متوفر بالمخزن بكميات منتظمة، ويمكن حجز كمية المشروع مسبقاً.',
      'التوصيل إلى الموقع بالشاحنة أو الصهريج حسب الكمية والطريق.',
      'يُباع بالكيس، والحد الأدنى للطلب كيس واحد.',
      'يُخزن مغطى في مكان جاف بعيداً عن الماء وقبل تاريخ الصلاحية.',
    ),
    isNew: false,
    isFeatured: true,
    unit: 'كيس',
    stock: 260,
    createdAt: '2026-06-12',
  },
  {
    id: 'p2',
    slug: 'rebar-12mm',
    name: 'حديد تسليح 12 مم',
    type: 'مواد إنشائية',
    categoryId: 'structural',
    description: 'قضبان تسليح للأعمال الإنشائية والأساسات. تُباع بالكيلوغرام مع إمكانية تقطيع الأطوال حسب الطلب داخل حدود المخزن.',
    price: 1600,
    image: media('rebar'),
    images: [media('rebar'), media('cement'), media('brick')],
    colors: [
      color('black-steel', 'أسود فولاذي', '#3a3f43', 640),
      color('rust', 'بني مؤكسد', '#7a5c46', 120),
    ],
    specs: {
      material: 'فولاذ تسليح',
      size: 'قطر 12 مم / طول 12 م',
      weight: 'يُحسب بالكيلوغرام',
      install: 'يُثبّت حسب تصميم المهندس والكابل المطلوب',
      finish: 'سطح فولاذي ناعم',
      supply: 'تقطيع وتوصيل حسب الكمية والطريق',
      use: 'أساسات، أعمدة، أسقف وسلالم',
      care: 'يُحفظ في مكان مرتفع بعيداً عن تجمع الماء لتفادي الصدأ',
    },
    faqs: faqs(
      'متوفر بالمخزن، وتحدد الكمية النهائية بعد معاينة الطلب.',
      'يُنقل بالشاحنة، ويمكن ترتيب الرفع في مواقع البناء.',
      'يُباع بالكيلوغرام، وتُحسب الأطوال حسب التقطيع المطلوب.',
      'يُرفع عن الأرض ويُغطى عند تركيبة لفترات طويلة.',
    ),
    isNew: false,
    isFeatured: true,
    unit: 'كغ',
    stock: 640,
    createdAt: '2026-05-28',
  },
  {
    id: 'p3',
    slug: 'red-brick',
    name: 'طوب أحمر عادي',
    type: 'مواد إنشائية',
    categoryId: 'structural',
    description: 'طوب أحمر للجدران والفصلات، مفرّز ومرتب لتسهيل التحميل. مناسب للأعمال السكنية والتجارية مع إمكانية توريد الكميات على دفعات.',
    price: 150,
    image: media('brick'),
    images: [media('brick'), media('cement'), media('tile-wall')],
    colors: [
      color('red', 'أحمر', '#b4553a', 4200),
      color('dark-red', 'أحمر غامق', '#8d4230', 900),
    ],
    specs: {
      material: 'طين محروق',
      size: 'قياس قياسي للجدران',
      weight: 'للقطعة الواحدة',
      install: 'يُركّب بمونة إسمنتية حسب السماكة المطلوبة',
      finish: 'سطح خشن يقبل التكسية',
      supply: 'توريد بالمتر المكعب أو بالألف',
      use: 'جدران خارجية وداخلية وفواصل',
      care: 'يُحفظ في مكان مرتب ومحايد الرطوبة قبل الاستخدام',
    },
    faqs: faqs(
      'متوفر بكميات كبيرة ويُحجز مسبقاً للمشاريع.',
      'يُفرّغ في الموقع وتُرتب الطبقات حسب مساحة التخزين.',
      'يُباع بالقطعة أو بالألف حسب طلب الموقع.',
      'يُرفع عن تجمع المياه ويُغطى عند التخزين الطويل.',
    ),
    isNew: false,
    isFeatured: false,
    unit: 'طوبة',
    stock: 4200,
    createdAt: '2026-04-02',
  },
  {
    id: 'p4',
    slug: 'floor-tile-60x60',
    name: 'سيراميك أرضيات 60×60',
    type: 'بلاط وسيراميك',
    categoryId: 'tiles',
    description: 'بلاط سيراميك للأرضيات بمقاس 60×60 سم، مناسب لغرف المعيشة والممرات والمحلات. متوفر درجات محايدة سهلة التنسيق مع باقي الديكور.',
    price: 6500,
    image: media('tile-floor'),
    images: [media('tile-floor'), media('porcelain'), media('tile-wall')],
    colors: [
      color('beige', 'بيج', '#d6c6ae', 90),
      color('grey', 'رمادي', '#a9aca8', 60),
      color('white', 'أبيض', '#f1efe9', 40),
      color('sand', 'رملي', '#cbb896', 30),
    ],
    specs: {
      material: 'سيراميك مصهور',
      size: '60 × 60 سم',
      weight: 'الكرتونة تكفي متر مربع تقريباً',
      install: 'يُركّب بمونة لاصقة على أرضية مستوية ومجهزة',
      finish: 'سطح مصقول متوسط اللمعة',
      supply: 'متوفر بالكرتون والطلب حسب المتر المربع',
      use: 'أرضيات غرف المعيشة والممرات والمحلات',
      care: 'تنظيف بماء ومنظف محايد، وتجنّب الصدمات الحادة',
    },
    faqs: faqs(
      'متوفر بالمخزن، وتُراجع الكميات حسب اللون المختار.',
      'التوصيل للموقع، والتركيب يتم بواسطة فريق الموقع.',
      'يُباع بالمتر المربع، ويُنصح بطلب5٪ إضافية للهالك.',
      'يُنظف بمنظف محايد ويُجفف بعد الغسل لتفادي البقع.',
    ),
    isNew: false,
    isFeatured: true,
    unit: 'متر مربع',
    stock: 180,
    createdAt: '2026-07-14',
  },
  {
    id: 'p5',
    slug: 'wall-tile-30x60',
    name: 'بلاط حائط 30×60',
    type: 'بلاط وسيراميك',
    categoryId: 'tiles',
    description: 'بلاط حائط بمقاس 30×60 سم للمطابخ ودورات المياه والممرات. يتوفر بدرجات فاتحة تسهّل تنظيف الجدران وتوسيع المكان بصرياً.',
    price: 5200,
    image: media('tile-wall'),
    images: [media('tile-wall'), media('tile-floor'), media('porcelain')],
    colors: [
      color('white', 'أبيض', '#f4f2ec', 70),
      color('beige', 'بيج', '#ddd0b8', 45),
      color('grey', 'رمادي داكن', '#8e9391', 30),
    ],
    specs: {
      material: 'سيراميك مزجج',
      size: '30 × 60 سم',
      weight: 'الكرتونة تكفي متر مربع تقريباً',
      install: 'يُركّب على جدار معوجّر بعد التسوية',
      finish: 'مزجج لامع سهل التنظيف',
      supply: 'متوفر بالكرتون مع إمكانية المزج بين الدرجات',
      use: 'مطابخ، دورات مياه، ممرات وواجهات داخلية',
      care: 'تنظيف بقطعة قماش ومنظف خفيف بعيداً عن الحمض',
    },
    faqs: faqs(
      'متوفر بالمخزن بثلاث درجات لونية أساسية.',
      'يُوصل للموقع وتُنصح بإضافة5٪ هالك لعملية القص.',
      'يُباع بالمتر مربع، ويُحسب مع الهالك قبل الطلب.',
      'يُنظف بمنظف محايد ويُشطف بالماء مباشرة.',
    ),
    isNew: true,
    isFeatured: true,
    unit: 'متر مربع',
    stock: 96,
    createdAt: '2026-09-08',
  },
  {
    id: 'p6',
    slug: 'porcelain-80x80',
    name: 'بورسلين لامع 80×80',
    type: 'بلاط وسيراميك',
    categoryId: 'tiles',
    description: 'بلاط بورسلين بمقاس 80×80 سم وتشطيب لامع، مخصص للأماكن الواسعة والمداخل. مقاوم للاستهلاك اليومي ويعطي امتداداً بصرياً واضحاً.',
    price: 9800,
    image: media('porcelain'),
    images: [media('porcelain'), media('tile-floor'), media('tile-wall')],
    colors: [
      color('white', 'أبيض لامع', '#f6f5f1', 30),
      color('grey', 'رمادي', '#b0b3af', 24),
    ],
    specs: {
      material: 'بورسلين مضغوط',
      size: '80 × 80 سم',
      weight: 'وزن ثقيل يقلل الكسر عند النقل',
      install: 'يُركّب بمونة عالية اللاصقة على أرضية مستوية',
      finish: 'لمعان مرتفع يعكس الإضاءة',
      supply: 'يُطلب مسبقاً حسب اللون والكمية',
      use: 'مداخل صالات، صوامع المطاعم والمحلات',
      care: 'منع ماء النظافة الحمضية والمواد الكاشطة',
    },
    faqs: faqs(
      'يتوفر بكميات محدودة ويُفضّل حجز الكمية قبل أسبوع.',
      'يُنقل بعناية وتُرتب الطبقات بفاصل واقٍ.',
      'يُباع بالمتر مربع مع مراعاة الهالك في القص.',
      'يُنظف بماء ومنظف محايد ويُجفف بعد ذلك.',
    ),
    isNew: true,
    isFeatured: false,
    unit: 'متر مربع',
    stock: 54,
    createdAt: '2026-09-16',
  },
  {
    id: 'p7',
    slug: 'ceramic-basin',
    name: 'حوض حمام بورسلين',
    type: 'مواد صحية',
    categoryId: 'sanitary',
    description: 'حوض غسيل بورسلين بتصميم بسيط وسطح سهل التنظيف، يصلح للمطابخ الصغيرة ودورات المياه. يُورّد مع توصيل يحفظ الحافة أثناء النقل.',
    price: 85000,
    image: media('basin'),
    images: [media('basin'), media('faucet'), media('toilet')],
    colors: [
      color('white', 'أبيض', '#f7f6f2', 22),
      color('grey', 'رمادي فاتح', '#d9dbd8', 8),
    ],
    specs: {
      material: 'بورسلين مزجج',
      size: 'مقاس قياسي للمغسلة',
      weight: 'خفيف نسبياً يسهّل التركيب',
      install: 'يُركّب على حامل أو خزان مع توصيل الماء والصرف',
      finish: 'سطح زجاجي لامع',
      supply: 'متوفر للمحلات والمشاريع بعد التأكيد',
      use: 'دورات المياه والمطابخ والخدمات',
      care: 'تنظيف بماء ومنظف خفيف وتجنّب الصباغات الكاشطة',
    },
    faqs: faqs(
      'متوفر بالمخزن باللون الأبيض، وباقي الدرجات بالطلب.',
      'التوصيل للموقع مع إمكانية طلب تركيب من فريقنا.',
      'يُباع بالقطعة، والحد الأدنى قطعة واحدة.',
      'يُنظف بقماش لطيف بعيداً عن المواد الكاشطة.',
    ),
    isNew: false,
    isFeatured: true,
    unit: 'قطعة',
    stock: 22,
    createdAt: '2026-06-30',
  },
  {
    id: 'p8',
    slug: 'toilet-ceramic-set',
    name: 'مرحاض بورسلين بغطاء',
    type: 'مواد صحية',
    categoryId: 'sanitary',
    description: 'مرحاض بورسلين متكامل بغطاء جلوس، مناسب للاستخدام اليومي في السكن والمكاتب. يُوفر معه عبوة التركيب الأساسية عند الطلب.',
    price: 98000,
    image: media('toilet'),
    images: [media('toilet'), media('basin'), media('tank')],
    colors: [
      color('white', 'أبيض', '#f7f6f2', 14),
      color('bone', 'عاجي', '#ece5d6', 6),
    ],
    specs: {
      material: 'بورسلين مزجج',
      size: 'مقاس قياسي مع خزان علوي',
      weight: 'يُنقل في علبة واحدة',
      install: 'يُركّب على تغذية وصرف جاهزة مع عزل أسفل القاعدة',
      finish: 'زجاجي لامع',
      supply: 'متوفر للمشروعات بعد تأكيد الكمية',
      use: 'دورات المياه السكنية والتجارية',
      care: 'منظف محايد دورياً مع الانتباه لعوامل الإحكام',
    },
    faqs: faqs(
      'متوفر بالمخزن باللون الأبيض.',
      'التوصيل للموقع مع إمكانية طلب فني التركيب.',
      'يُباع بالقطعة كاملة بما فيها الغطاء.',
      'يُنظف بمنظف محايد ويُشطف جيداً بعد الاستخدام.',
    ),
    isNew: false,
    isFeatured: true,
    unit: 'قطعة',
    stock: 14,
    createdAt: '2026-05-19',
  },
  {
    id: 'p9',
    slug: 'water-tank-500l',
    name: 'خزان ماء بلاستيك 500 لتر',
    type: 'مواد صحية',
    categoryId: 'sanitary',
    description: 'خزان ماء مصمت بسعة 500 لتر للأسطح والخدمات، بجدار سميك يتحمل التعرض للشمس. مناسب للمنازل والمحلات والورش.',
    price: 155000,
    image: media('tank'),
    images: [media('tank'), media('faucet'), media('basin')],
    colors: [
      color('white', 'أبيض', '#f2f2ee', 9),
      color('blue', 'أزرق', '#3f7fb5', 5),
    ],
    specs: {
      material: 'بولي إيثيلين عالي الكثافة',
      size: 'سعة 500 لتر',
      weight: 'خفيف نسبياً مع تقوية في الجدران',
      install: 'يُركّب على قاعدة مستوية مع ربط المدخل والمخرج',
      finish: 'سطح مصمت مقاوم للأشعة',
      supply: 'يُطلب مسبقاً حسب اللون والكمية',
      use: 'تخزين مياه الأسطح والخدمات والمواقع',
      care: 'تفريغ دوري والتأكد من نظافة الفتحات',
    },
    faqs: faqs(
      'متوفر بالمخزن باللونين الأبيض والأزرق.',
      'يُنقل إلى الموقع ويُرفع بواسطة الرافعة أو السلالم.',
      'يُباع بالقطعة، ويُنصح بتحديد موضع التركيب مسبقاً.',
      'يُنظف دورياً ويُترك بعيداً عن مصادر التسخين المباشرة.',
    ),
    isNew: true,
    isFeatured: false,
    unit: 'قطعة',
    stock: 9,
    createdAt: '2026-09-04',
  },
  {
    id: 'p10',
    slug: 'basin-faucet',
    name: 'خلاط حوض حمام',
    type: 'مواد صحية',
    categoryId: 'sanitary',
    description: 'خلاط ماء لحوض الغسيل بتشطيب كروم، بحركة صنبور مريحة وتوصيل مياه ساخنة وباردة. مناسب للمطابخ ودورات المياه.',
    price: 48000,
    image: media('faucet'),
    images: [media('faucet'), media('basin'), media('toilet')],
    colors: [
      color('chrome', 'كروم', '#c9ced4', 26),
      color('gold', 'ذهبي', '#c8a24a', 7),
    ],
    specs: {
      material: 'نحاس مطلي بالكروم',
      size: 'ارتفاع مناسب لحوض الغسيل',
      weight: 'قطعة واحدة مع إكسسوارات التثبيت',
      install: 'يُركّب على فتحة الحوض مع خراطيم التغذية',
      finish: 'كروم لامع أو ذهبي',
      supply: 'متوفر بالمخزن مع إمكانية الطلب باللون',
      use: 'أحواض المطابخ ودورات المياه',
      care: 'مسح جاف بعد الاستخدام لتفادي بقع الماء',
    },
    faqs: faqs(
      'متوفر بتشطيب كروم، والذهبي بالطلب.',
      'يُوصل للموقع ويمكن طلب فني التركيب معه.',
      'يُباع بالقطعة مع خراطيم التوصيل.',
      'يُمسح بقماش لطيف بعيداً عن المواد الكاشطة.',
    ),
    isNew: false,
    isFeatured: false,
    unit: 'قطعة',
    stock: 26,
    createdAt: '2026-07-22',
  },
  {
    id: 'p11',
    slug: 'interior-paint-matte',
    name: 'دهان داخلي مطفي',
    type: 'أصباغ ومعاجين',
    categoryId: 'paints',
    description: 'دهان داخلي بتشطيب مطفي يعطي جداراً نظيفاً بلا انعكاسات، مناسب لغرف المعيشة والمكاتب. يتوفر بدرجات فاتحة تُخلط عند الطلب.',
    price: 42000,
    image: media('paint-matte'),
    images: [media('paint-matte'), media('paint-exterior'), media('plaster')],
    colors: [
      color('white', 'أبيض', '#f5f4ef', 38),
      color('beige', 'بيج', '#e3d7c2', 26),
      color('grey', 'رمادي فاتح', '#cfd2cd', 18),
      color('sage', 'أخضر فاتح', '#c8d3c2', 12),
      color('sky', 'أزرق فاتح', '#c6d6e2', 12),
    ],
    specs: {
      material: 'أكريليك مائي',
      size: 'عبوة 15 لتر تقريباً',
      weight: 'عبوة كاملة',
      install: 'يُطبّق بrod roller على سطح مكتمل المعاجنة',
      finish: 'مطفي متجانس',
      supply: 'تُخلط الدرجة المطلوبة بعد تأكيد الطلب',
      use: 'جدران وسقوف الأماكن الداخلية',
      care: 'يُحفظ مغلقاً بعيداً عن التجمد والشمس المباشرة',
    },
    faqs: faqs(
      'متوفر بالمخزن، وتُخلط الدرجات حسب الطلب.',
      'التوصيل للموقع، والتطبيق بواسطة فريق الموقع أو المقاول.',
      'يُباع بالعبوة، وتُحسب الكمية حسب مساحة السطح.',
      'يُخزن في مكان بارد ومغلق، ويُمنع التخزين بعد فتح العبوة.',
    ),
    isNew: false,
    isFeatured: true,
    unit: 'عبوة',
    stock: 38,
    createdAt: '2026-06-05',
  },
  {
    id: 'p12',
    slug: 'exterior-paint',
    name: 'دهان خارجي مقاوم للعوامل الجوية',
    type: 'أصباغ ومعاجين',
    categoryId: 'paints',
    description: 'دهان خارجي يتحمل الشمس والغبار والأمطار، مناسب للواجهات والأسوار والمباني الخارجية. يحافظ على لونه فترة أطول من الدهانات الداخلية.',
    price: 68000,
    image: media('paint-exterior'),
    images: [media('paint-exterior'), media('paint-matte'), media('plaster')],
    colors: [
      color('white', 'أبيض', '#f3f2ec', 21),
      color('sand', 'رملي', '#dfceb0', 14),
      color('grey', 'رمادي', '#b9bcb7', 11),
      color('green', 'أخضر داكن', '#6f8a74', 8),
    ],
    specs: {
      material: 'أكريليك خارجي مع واقي فوق بنفسجي',
      size: 'عبوة 15 لتر تقريباً',
      weight: 'عبوة كاملة',
      install: 'يُطبّق على سطح جاف ومكتمل التجهيز بطبقتين',
      finish: 'مطفي خارجي متجانس',
      supply: 'تُخلط الدرجة بعد تأكيد الطلب والكمية',
      use: 'واجهات المباني، الأسوار والأعمدة الخارجية',
      care: 'يُغلق بعد كل استخدام ويُحفظ بعيداً عن التجمد',
    },
    faqs: faqs(
      'متوفر بالمخزن، وتُنصح بطلب الكمية دفعة واحدة للون واحد.',
      'يُوصل للموقع ويُنصح بتطبيقه في جو معتدل دون مطر.',
      'يُباع بالعبوة وتُحسب الكمية حسب مساحة الواجهة.',
      'يُخزن مغلقاً ومائلاً قليلاً لمنع التجمد في الشتاء.',
    ),
    isNew: true,
    isFeatured: true,
    unit: 'عبوة',
    stock: 21,
    createdAt: '2026-09-12',
  },
  {
    id: 'p13',
    slug: 'plaster-bag',
    name: 'معجون جبس (بلاستر)',
    type: 'أصباغ ومعاجين',
    categoryId: 'paints',
    description: 'معجون جبس لجباية الجدران قبل الدهان، بملمس ناعم يسهل صقله. مناسب لسدّ الفراغات وتجهيز الأسطح الداخلية.',
    price: 9500,
    image: media('plaster'),
    images: [media('plaster'), media('paint-matte'), media('cement')],
    colors: [
      color('white', 'أبيض جبسي', '#f6f4ee', 140),
      color('grey', 'رمادي فاتح', '#dcddd7', 40),
    ],
    specs: {
      material: 'جبس مطفي جاهز للخلط',
      size: 'كيس 25 كغ',
      weight: '25 كغ',
      install: 'يُخلط بالماء حتى نعومة الجبنة ثم يُطبّق بالسكين',
      finish: 'أبيض مطفي قابل للصقل',
      supply: 'متوفر بالمخزن للطلبات الفردية والمشاريع',
      use: 'جباية الجدران والأسقف قبل الدهان',
      care: 'يُحفظ في مكان جاف والكيس مغلق بعد الفتح',
    },
    faqs: faqs(
      'متوفر بالمخزن بكميات منتظمة.',
      'يُوصل للموقع ويُخلط مباشرة قبل الاستعمال.',
      'يُباع بالكيس، والحد الأدنى كيس واحد.',
      'يُخزن مغطى في مكان جاف بعيداً عن الرطوبة.',
    ),
    isNew: false,
    isFeatured: false,
    unit: 'كيس',
    stock: 140,
    createdAt: '2026-08-11',
  },
  {
    id: 'p14',
    slug: 'paint-roller-kit',
    name: 'طقم فرش وبكرات دهان',
    type: 'أدوات ولوازم',
    categoryId: 'tools',
    description: 'طقم تطبيق للدهان يشمل بكرة عريضة وفرشاة ومقبض ممتد، يصلح لأعمال الدهان الداخلية والخارجية في المنازل والمحلات.',
    price: 12500,
    image: media('roller'),
    images: [media('roller'), media('paint-matte'), media('safety')],
    colors: [
      color('blue', 'أزرق', '#2f6ea8', 30),
      color('black', 'أسود', '#2c3033', 16),
    ],
    specs: {
      material: 'بلاستيك مقوّاة وليف صناعي',
      size: 'بكرة 25 سم مع مقبض ممتد',
      weight: 'طقم كامل',
      install: 'جاهز للاستخدام بعد تثبيت المقبض',
      finish: 'ملمس ليڤ متساوي لطبقة متجانسة',
      supply: 'متوفر بالمخزن للمحلات والأفراد',
      use: 'دهان الجدران والأسواق والأعمال اليومية',
      care: 'يُنظف بعد كل استخدام ويُجفف قبل التخزين',
    },
    faqs: faqs(
      'متوفر بالمخزن بحجمين مختلفين.',
      'يُوصل مع الطلب ولا يحتاج تركيب.',
      'يُباع كطقم واحد، ويمكن طلب قطع إضافية.',
      'يُغسل بالماء بعد الاستخدام ويُجفف في الظل.',
    ),
    isNew: false,
    isFeatured: false,
    unit: 'طقم',
    stock: 30,
    createdAt: '2026-07-01',
  },
  {
    id: 'p15',
    slug: 'worker-safety-kit',
    name: 'طقم أدوات حماية العمال',
    type: 'أدوات ولوازم',
    categoryId: 'tools',
    description: 'طقم حماية أساسي للموقع يشمل خوذة وقفازات ونظارة، مناسب لفرق التركيب وأعمال التحميل والتفريغ داخل المستودع.',
    price: 18500,
    image: media('safety'),
    images: [media('safety'), media('roller'), media('brick')],
    colors: [
      color('yellow', 'أصفر', '#e3b23c', 24),
      color('white', 'أبيض', '#f1f0ea', 12),
    ],
    specs: {
      material: 'بلاستيك صلب وقماش مقوى',
      size: 'مقاس موحد قابل للضبط',
      weight: 'طقم كامل',
      install: 'جاهز للاستخدام مباشرة',
      finish: 'سطح مقاوم للاحتكاك',
      supply: 'متوفر بالمخزن للمقاولين والأفراد',
      use: 'تحميل وتفريغ وتركيب داخل الموقع',
      care: 'يُنظف بعد كل استخدام ويُستبدل عند التآكل',
    },
    faqs: faqs(
      'متوفر بالمخزن بالألوان المتوفرة.',
      'يُوصل مع الطلب ولا يحتاج تركيب.',
      'يُباع كطقم واحد.',
      'يُفحص قبل كل استخدام ويُستبدل عند ظهور التشقق.',
    ),
    isNew: false,
    isFeatured: false,
    unit: 'طقم',
    stock: 30,
    createdAt: '2026-08-02',
  },
]

export const fallbackRoutes: SiteRoute[] = [
  { id: 'home', label: 'الرئيسية', path: '/', header: true },
  { id: 'catalog', label: 'المنتجات', path: '/catalog', header: true },
  { id: 'new', label: 'وصل حديثاً', path: '/catalog?sort=newest', header: true },
  { id: 'favorites', label: 'المفضلة', path: '/favorites', header: false },
  { id: 'about', label: 'من نحن', path: '/about', header: true },
  { id: 'guide', label: 'دليل المواد', path: '/fabric-guide', header: true },
  { id: 'contact', label: 'تواصل معنا', path: '/contact', header: false },
  { id: 'tracking', label: 'تتبع الطلب', path: '/order-tracking', header: false },
  { id: 'policies', label: 'السياسات', path: '/policies', header: false },
]

export const governorates = [
  'بغداد', 'البصرة', 'نينوى', 'أربيل', 'النجف', 'كربلاء', 'الأنبار', 'ديالى',
  'كركوك', 'صلاح الدين', 'واسط', 'بابل', 'ذي قار', 'ميسان', 'المثنى', 'القادسية', 'دهوك', 'السليمانية',
]

export const guideQuestions: ProductFaq[] = [
  { question: 'كيف أحسب كمية السيراميك للمكان؟', answer: 'احسب المساحة بالمتر المربع ثم أضف 5 إلى 10٪ هالك للقص والكسر. راجعي مقاس البلاط قبل الشراء لأن القص يغيّر عدد الكراتين المطلوبة.' },
  { question: 'ما الفرق بين الدهان الداخلي والخارجي؟', answer: 'الدهان الداخلي يركّز على النظافة واندماج اللون مع الجدار، أما الخارجي فيتحمل الشمس والمطر والغبار، لذلك يُفضّل استخدامه على الواجهات والأسوار.' },
  { question: 'كيف أحسب الكميات الإنشائية؟', answer: 'كميات الإسمنت والحديد والطوب تُحسب حسب تصميم المهندس ومساحة الموقع. أرسل لنا المساحات وسنقترح الكميات التقريبية قبل التوريد.' },
  { question: 'هل توفرون التوصيل للمشاريع؟', answer: 'نعم، التوصيل متاح إلى جميع المحافظات، ويمكن تنسيق التوريد على دفعات متتابعة لتناسب وتيرة العمل في الموقع.' },
  { question: 'كيف أختار درجة اللون المناسبة؟', answer: 'خذ عينة من الدرجة إلى مكان المشروع وقارنها بالإضاءة النهارية والمساحات المجاورة قبل تثبيت الطلب، فاللون يتغيّر بين الضوء الطبيعي والصناعي.' },
]

export const trustItems = [
  { title: 'توصيل لكل العراق', description: 'جميع المحافظات', icon: 'truck' },
  { title: 'توريد للمشاريع', description: 'كميات بالجملة', icon: 'check' },
  { title: 'استشارة عبر واتساب', description: 'قبل الطلب وبعده', icon: 'message' },
  { title: 'علامات معتمدة', description: 'وكيل رسمي', icon: 'globe' },
] as const

export const homeStory = {
  title: 'الصفا في كلمة',
  text: 'شركة اخوان الصفا تمثل علامات تجارية متخصصة في المواد الإنشائية والصحية والأصباغ، وتجمع بين المخزون الجاهز والتوريد المنظم للمشاريع والمحال في كل المحافظات.',
}
