#!/usr/bin/env python3
"""Turn data/products.json + data/categories.json into a D1 seed file."""
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DATA = os.path.join(REPO, "data")
OUT = os.path.join(DATA, "seed.sql")

DROP_NOTE = "-- EVA STORE seed (generated by tools/build_seed_sql.py)\n"

ROUTES = [
    ("route-catalog", "كل الأقمشة", "/catalog", 1, 1),
    ("route-embroidered", "مطرز", "/catalog?category=embroidered", 1, 2),
    ("route-plain", "سادة", "/catalog?category=plain", 1, 3),
    ("route-stretch", "مطاطي", "/catalog?category=stretch", 1, 4),
    ("route-sequined", "ترتر ولمّاع", "/catalog?category=sequined", 1, 5),
    ("route-patterned", "مزخرف", "/catalog?category=patterned", 1, 6),
    ("route-info", "معلومات", "/about", 1, 7),
    ("route-guide", "دليل الأقمشة", "/fabric-guide", 1, 8),
    ("route-contact", "تواصلي معنا", "/contact", 1, 9),
    ("route-tracking", "تتبع الطلب", "/order-tracking", 1, 10),
]


def q(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    products = json.load(open(os.path.join(DATA, "products.json"), encoding="utf-8"))
    categories = json.load(open(os.path.join(DATA, "categories.json"), encoding="utf-8"))
    lines = [DROP_NOTE, "DELETE FROM products;", "DELETE FROM categories;", "DELETE FROM routes;"]

    for cat in sorted(categories, key=lambda item: item.get("sort_order", 0)):
        lines.append(
            "INSERT INTO categories (id, slug, name, description, image, accent, sort_order) VALUES "
            f"({q(cat.get('id'))}, {q(cat.get('slug'))}, {q(cat.get('name'))}, {q(cat.get('description', ''))}, "
            f"{q(cat.get('image', ''))}, {q(cat.get('accent', '#7a5a6b'))}, {q(cat.get('sort_order', 0))});"
        )

    for row in ROUTES:
        lines.append(
            "INSERT INTO routes (id, label, path, header, sort_order) VALUES "
            f"({q(row[0])}, {q(row[1])}, {q(row[2])}, {row[3]}, {row[4]});"
        )

    for product in products:
        specs = product.get("specs") or {}
        colors = product.get("colors") or []
        images = product.get("images") or [product.get("image", '')]
        faqs = product.get("faqs") or []
        lines.append(
            "INSERT INTO products (id, slug, name, type, category_id, description, price, compare_at_price, image, "
            "images_json, colors_json, specs_json, faqs_json, colors_enabled, is_new, is_featured, hidden, "
            "stock_meters, source_url, origin, sort_order, created_at, updated_at, video) VALUES ("
            f"{q(product['slug'])}, {q(product['slug'])}, {q(product['name'])}, {q(product.get('type', ''))}, "
            f"{q(product.get('categoryId', 'plain'))}, {q(product.get('description', ''))}, {q(product.get('price', 0))}, "
            f"NULL, {q(product.get('image', ''))}, {q(json.dumps(images, ensure_ascii=False))}, "
            f"{q(json.dumps(colors, ensure_ascii=False))}, {q(json.dumps(specs, ensure_ascii=False))}, "
            f"{q(json.dumps(faqs, ensure_ascii=False))}, {q(bool(product.get('colorsEnabled', False)))}, "
            f"{q(bool(product.get('isNew', False)))}, {q(bool(product.get('isFeatured', False)))}, "
            f"{q(bool(product.get('hidden', False)))}, "
            f"{q(product.get('stockMeters', 0))}, {q(product.get('sourceUrl', ''))}, 'seed', "
            f"{q(product.get('sort_order', 0))}, {q(product.get('createdAt', '2026-10-06'))}, datetime('now'), "
            f"{q(product.get('video'))});"
        )

    open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(products)} products, {os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    main()
